# =============================================================================
# llm/reward_generator.py — Call LLM, extract + validate Python code, save it
# =============================================================================

import ast
import os
import re
import shutil
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from google import genai
from google.genai import types

from config import LLM_API_KEY, MODEL_NAME, REWARD_FILE, REWARD_ARCHIVE


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _extract_code(raw_text: str) -> str:
    """
    Extract the Python function from the LLM response.

    Handles two cases:
      1. Wrapped in a ```python ... ``` code fence
      2. Raw Python text (no fence)
    """
    # Try to find a fenced code block
    fence_match = re.search(r"```(?:python)?\s*(.*?)```", raw_text, re.DOTALL)
    if fence_match:
        return fence_match.group(1).strip()

    # Fall back: return the full response stripped of whitespace
    return raw_text.strip()


def _validate_code(code: str) -> bool:
    """
    Run two safety checks:
      1. The code must parse as valid Python (ast).
      2. It must define a function named `compute_reward`.

    Returns True if valid, False otherwise.
    """
    try:
        tree = ast.parse(code)
    except SyntaxError as exc:
        print(f"[reward_generator] Syntax error: {exc}")
        return False

    fn_names = [
        node.name for node in ast.walk(tree)
        if isinstance(node, ast.FunctionDef)
    ]
    if "compute_reward" not in fn_names:
        print("[reward_generator] 'compute_reward' function not found in generated code.")
        return False

    return True


def _archive_reward(iteration: int) -> None:
    """Copy current_reward.py to rewards/archive/reward_iter_<N>.py."""
    os.makedirs(REWARD_ARCHIVE, exist_ok=True)
    dst = os.path.join(REWARD_ARCHIVE, f"reward_iter_{iteration}.py")
    shutil.copy2(REWARD_FILE, dst)
    print(f"[reward_generator] Archived reward → {dst}")


def _save_reward(code: str) -> None:
    """Overwrite rewards/current_reward.py with the validated code."""
    os.makedirs(os.path.dirname(os.path.abspath(REWARD_FILE)), exist_ok=True)

    header = (
        "# Auto-generated by LLM — do not edit by hand.\n"
        "# Modify llm/prompt_builder.py or logs/human_hint.txt to influence the next iteration.\n\n"
        "import numpy as np\n\n"
    )
    with open(REWARD_FILE, "w", encoding="utf-8") as f:
        f.write(header + code + "\n")
    print(f"[reward_generator] New reward saved → {REWARD_FILE}")


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_reward(prompt: str, iteration: int) -> bool:
    """
    Send `prompt` to the LLM, extract + validate the reward function,
    and (if valid) overwrite rewards/current_reward.py.

    Args:
        prompt:    the full prompt string from llm/prompt_builder.py
        iteration: current loop iteration used for archiving

    Returns:
        True  — new reward saved successfully
        False — generation/validation failed; old reward kept
    """
    # Resolve API key: prefer env var, fall back to config
    api_key = os.environ.get("GEMINI_API_KEY", LLM_API_KEY)
    if not api_key or api_key == "YOUR_GEMINI_API_KEY_HERE":
        print("[reward_generator] ERROR: No valid Gemini API key found.\n"
              "  Set the GEMINI_API_KEY environment variable or update config.py.")
        return False

    client = genai.Client(api_key=api_key)

    system_instruction = (
        "You are an expert RL researcher. "
        "Return ONLY the requested Python function, no explanations.\n\n"
    )
    full_prompt = system_instruction + prompt

    print(f"[reward_generator] Calling {MODEL_NAME} …")
    try:
        response = client.models.generate_content(
            model=MODEL_NAME,
            contents=full_prompt,
        )
    except Exception as exc:
        print(f"[reward_generator] Gemini API error: {exc}")
        return False

    raw_text = response.text
    print("[reward_generator] Raw LLM response:\n", raw_text[:500], "\n---")

    code = _extract_code(raw_text)

    if not _validate_code(code):
        print("[reward_generator] Validation failed — keeping previous reward.")
        return False

    # Archive the current reward before overwriting
    if os.path.isfile(REWARD_FILE):
        _archive_reward(iteration)

    _save_reward(code)
    return True
