# Auto-generated by LLM — do not edit by hand.
# Modify llm/prompt_builder.py or logs/human_hint.txt to influence the next iteration.

import numpy as np

import numpy as np

def compute_reward(obs, action):
    # Observation components
    hull_angle = obs[0]          # Torso tilt
    hull_angular_vel = obs[1]    # Torso angular velocity
    forward_vel = obs[2]         # Forward (x) velocity
    vertical_vel = obs[3]        # Vertical (y) velocity

    right_hip_angle = obs[4]
    right_knee_angle = obs[6]
    right_contact = obs[8]       # Right foot ground contact (1 if in contact, ~0 otherwise)

    left_hip_angle = obs[9]
    left_knee_angle = obs[11]
    left_contact = obs[13]       # Left foot ground contact (1 if in contact, ~0 otherwise)

    reward = 0.0

    # 1. Forward Progress (Goal 3: average_speed ↑)
    # Reward for positive forward velocity. This is the primary driver for locomotion.
    reward += forward_vel * 1.0

    # 2. Action Smoothness and Energy Efficiency (Goals 5, 6: energy_consumption ↓, action_smoothness ↓)
    # Penalize large actions to encourage smoother movement and energy efficiency.
    # Standard penalty from the environment for BipedalWalker-v3.
    reward -= np.sum(np.square(action)) * 0.00035

    # 3. Posture & Fall Prevention (Goal 1: ELIMINATE FALLS, Goal 4: UPRIGHT POSTURE)
    # These penalties are crucial given the 100% fall rate. They aim to prevent instability.

    # Hull angle: Target a slight forward lean (0.05-0.15 rad). Current torso_tilt is 0.0651.
    # Penalize deviation from this target strongly to maintain upright posture and prevent falls.
    hull_angle_target = 0.1 # radians, for a slight forward lean
    reward -= np.square(hull_angle - hull_angle_target) * 10.0 # Significantly increased weight

    # Hull angular velocity: Penalize high angular velocity to reduce wobbling and improve stability.
    # Current lateral_stability is 0.0095 (good, but needs strong maintenance).
    reward -= np.abs(hull_angular_vel) * 0.5 # Increased weight

    # Vertical velocity: Penalize strong negative vertical velocity, which indicates falling.
    reward -= max(0, -vertical_vel) * 5.0 # Significantly increased weight for direct fall prevention

    # 4. Human-like Gait Cycle (Goal 2: ACHIEVE HUMAN-LIKE GAIT CYCLE)
    # Encourage alternating swing/stance, target double/single support fractions, eliminate flight.

    # Define contact states based on observation values
    is_right_stance = right_contact > 0.5 and left_contact < 0.5
    is_left_stance = left_contact > 0.5 and right_contact < 0.5
    is_single_support = is_right_stance or is_left_stance
    is_double_support = right_contact > 0.5 and left_contact > 0.5
    is_flight = right_contact < 0.5 and left_contact < 0.5

    # Flight penalty: Very strong penalty to eliminate hopping/jumping (flight_fraction ≈ 0).
    if is_flight:
        reward -= 10.0 # Strongly discourages both feet off the ground

    # Double support reward: Encourage slight double support (target 0.1-0.2, current 0.068).
    if is_double_support:
        reward += 0.8 # Increased reward to boost double_support_fraction

    # Single support reward: Basic reward for being in single support.
    # (Current single_support_fraction 0.920 is too high, but implicit penalties from other terms
    # and encouragement of double support should help rebalance this).
    if is_single_support:
        reward += 0.3 # Small reward

    # 5. Stance Leg Straightness & Hip Position (Goal 7: stance_leg_straightness ↓, Goal 2)
    # When a leg is on the ground (stance phase), its knee should be relatively straight and hip neutral.
    # Current stance_leg_straightness: 0.1406 (good, but aim for <0.3 and lower).
    stance_knee_straight_target = 0.05 # Small knee angle for straightness
    stance_hip_target_offset = 0.0 # Hip should be relatively neutral (vertical) in stance

    if right_contact > 0.5: # Right leg is in stance
        reward -= np.abs(right_knee_angle - stance_knee_straight_target) * 2.0 # Increased penalty for bent knee
        reward -= np.square(right_hip_angle - stance_hip_target_offset) * 0.3 # Penalty for hip deviation from neutral

    if left_contact > 0.5: # Left leg is in stance
        reward -= np.abs(left_knee_angle - stance_knee_straight_target) * 2.0
        reward -= np.square(left_hip_angle - stance_hip_target_offset) * 0.3

    # 6. Swing Leg Motion & Gait Symmetry (Goal 2, 7: hip_angle_range ↑, gait_symmetry_index ↓)
    # When a leg is swinging, the hip should move forward, and the knee should bend for clearance.
    # Current hip_angle_range: 1.1735 (good, target >0.8).

    swing_hip_forward_reward_weight = 0.8   # Reward for positive hip angle (swinging forward)
    swing_hip_backward_penalty_weight = 1.5 # Penalize hip moving backward during swing
    swing_knee_bend_target = 0.7            # Target ~0.7 rad (~40 degrees) knee bend for clearance

    if right_contact < 0.5: # Right leg is in swing
        reward += max(0, right_hip_angle) * swing_hip_forward_reward_weight
        reward -= max(0, -right_hip_angle) * swing_hip_backward_penalty_weight
        reward -= np.square(right_knee_angle - swing_knee_bend_target) * 1.0 # Increased penalty for improper knee bend

    if left_contact < 0.5: # Left leg is in swing
        reward += max(0, left_hip_angle) * swing_hip_forward_reward_weight
        reward -= max(0, -left_hip_angle) * swing_hip_backward_penalty_weight
        reward -= np.square(left_knee_angle - swing_knee_bend_target) * 1.0

    # Gait Symmetry: Encourage alternating hip movements (anti-phase) for a smooth, symmetric gait.
    # Current gait_symmetry_index: 0.0653 (worsening, target 0).
    # Penalize if hip angles are too aligned (sum is high), promoting anti-phase motion.
    reward -= np.square(right_hip_angle + left_hip_angle) * 0.8 # Increased penalty for lack of hip anti-phase

    return reward
