# Auto-generated by LLM — do not edit by hand.
# Modify llm/prompt_builder.py or logs/human_hint.txt to influence the next iteration.

import numpy as np

import numpy as np

def compute_reward(obs, action):
    # Observation indices for clarity
    HULL_ANGLE = obs[0]
    HULL_ANG_VEL = obs[1]
    FORWARD_VEL = obs[2]
    # VERT_VEL = obs[3] # Not directly used for now, as altitude is implicitly handled by env termination
    HIP_R_ANGLE = obs[4]
    # HIP_R_ANG_VEL = obs[5] # Not directly used for now
    KNEE_R_ANGLE = obs[6]
    # KNEE_R_ANG_VEL = obs[7] # Not directly used for now
    FOOT_R_CONTACT = obs[8]
    HIP_L_ANGLE = obs[9]
    # HIP_L_ANG_VEL = obs[10] # Not directly used for now
    KNEE_L_ANGLE = obs[11]
    # KNEE_L_ANG_VEL = obs[12] # Not directly used for now
    FOOT_L_CONTACT = obs[13]

    reward = 0.0

    # 1. Forward Progress (High Priority)
    # Current average_speed is low (0.0223). Boost forward velocity reward.
    FORWARD_VEL_SCALE = 3.0
    reward += FORWARD_VEL_SCALE * FORWARD_VEL
    # Penalize backward movement more strongly
    if FORWARD_VEL < 0:
        reward += FORWARD_VEL_SCALE * FORWARD_VEL * 2 # Negative reward for backward motion

    # 2. Posture & Stability (Eliminate Falls, Upright Posture)
    # Goal: torso_tilt ~0.05-0.15 rad (slight forward lean)
    # Current torso_tilt is 0.0914 (good). Aim to maintain.
    TARGET_HULL_ANGLE = 0.08  # rad, slight forward lean
    HULL_ANGLE_PENALTY_SCALE = 8.0 # Strong penalty for significant deviations
    HULL_ANGLE_TOLERANCE = 0.04 # Allow minor deviations without penalty
    hull_angle_error = np.abs(HULL_ANGLE - TARGET_HULL_ANGLE)
    reward -= HULL_ANGLE_PENALTY_SCALE * np.maximum(0, hull_angle_error - HULL_ANGLE_TOLERANCE)

    # Penalize large hull angular velocity to prevent wobbling
    HULL_ANG_VEL_PENALTY_SCALE = 0.4
    reward -= HULL_ANG_VEL_PENALTY_SCALE * np.abs(HULL_ANG_VEL)

    # 3. Human-like Gait Cycle (MOST IMPORTANT for the specific request)
    # Goal: single_support_fraction ≈ 0.65, double_support_fraction ≈ 0.15, flight_fraction ≈ 0
    # Current: single_support 0.95 (too high), double_support 0.04 (too low), flight 0.006 (good)

    is_single_support = (FOOT_R_CONTACT != FOOT_L_CONTACT)
    is_double_support = (FOOT_R_CONTACT and FOOT_L_CONTACT)
    is_flight = (not FOOT_R_CONTACT and not FOOT_L_CONTACT)

    # Adjust rewards to shift balance towards more double support and less single support
    C_SINGLE_SUPPORT = 0.3 # Reduced to discourage excessive single support
    C_DOUBLE_SUPPORT = 0.6 # Increased to encourage more double support
    C_FLIGHT_PENALTY = 1.5 # Increased penalty to strictly discourage hopping

    if is_single_support:
        reward += C_SINGLE_SUPPORT
    if is_double_support:
        reward += C_DOUBLE_SUPPORT
    if is_flight:
        reward -= C_FLIGHT_PENALTY

    # Stance Leg Attributes (Straightness, Hip Position for push-off)
    # Current stance_leg_straightness is 0.1189 (good). Keep knee straight.
    C_STANCE_KNEE_PENALTY = 3.0 # Increased to enforce straighter knees
    C_STANCE_HIP_POSTURE = 0.8 # Reward for hip in good stance range (push-off / support)

    # Right leg is in stance
    if FOOT_R_CONTACT:
        # Penalize bent knee. KNEE_R_ANGLE is positive for bent knee.
        reward -= C_STANCE_KNEE_PENALTY * np.square(KNEE_R_ANGLE)
        # Reward hip angle for stance phase: slightly negative for push-off, or neutral for support
        # Gaussian centered around -0.2 rad (slight backward extension for propulsion)
        reward += C_STANCE_HIP_POSTURE * np.exp(-10 * np.square(HIP_R_ANGLE + 0.2))

    # Left leg is in stance
    if FOOT_L_CONTACT:
        reward -= C_STANCE_KNEE_PENALTY * np.square(KNEE_L_ANGLE)
        reward += C_STANCE_HIP_POSTURE * np.exp(-10 * np.square(HIP_L_ANGLE + 0.2))

    # Swing Leg Attributes (Knee flexion for clearance, Hip forward swing for stepping)
    # Current hip_angle_range is 1.1495 (good), hip_knee_coordination is 0.7752 (good).
    C_SWING_KNEE_FLEXION = 0.4 # Reward moderate knee flexion during swing
    C_SWING_HIP_FORWARD = 0.4 # Reward hip swinging forward for step

    # Right leg is in swing
    if not FOOT_R_CONTACT:
        # Reward knee bend for leg clearance, but not excessively (KNEE_R_ANGLE is positive for bend)
        reward += C_SWING_KNEE_FLEXION * np.clip(KNEE_R_ANGLE, 0.0, 1.0)
        # Reward hip moving forward for stepping: Gaussian around +0.6 rad (forward swing)
        reward += C_SWING_HIP_FORWARD * np.exp(-5 * np.square(HIP_R_ANGLE - 0.6))

    # Left leg is in swing
    if not FOOT_L_CONTACT:
        reward += C_SWING_KNEE_FLEXION * np.clip(KNEE_L_ANGLE, 0.0, 1.0)
        reward += C_SWING_HIP_FORWARD * np.exp(-5 * np.square(HIP_L_ANGLE - 0.6))

    # 4. Energy Efficiency (action_cost)
    # Current energy_consumption is worsening (2387.7058). Increase penalty for motor torques.
    ACTION_COST_SCALE = 0.0005 # Increased from 0.00035 (default in many BipedalWalker variants)
    reward -= ACTION_COST_SCALE * np.sum(np.square(action))

    return float(reward)
