# Auto-generated by LLM — do not edit by hand.
# Modify llm/prompt_builder.py or logs/human_hint.txt to influence the next iteration.

import numpy as np

import numpy as np

def compute_reward(obs, action):
    # Constants for reward scaling and targets
    SURVIVAL_BONUS = 1.0

    # Basic Locomotion
    X_VELOCITY_WEIGHT = 2.5 # Prioritize forward progress

    # Posture and Stability
    HULL_ANGLE_TARGET = 0.1 # Ideal slight forward lean in radians (0.05-0.15 rad)
    HULL_ANGLE_PENALTY_SCALE = 5.0 # Stronger penalty for deviation from target hull angle
    HULL_ANGULAR_VELOCITY_PENALTY_SCALE = 0.15 # Penalty for torso wobbling

    # Fall prevention
    Y_VELOCITY_FALLING_THRESHOLD = -0.1 # Below this, consider it falling significantly
    Y_VELOCITY_FALLING_PENALTY_SCALE = 20.0 # Very strong penalty for negative vertical velocity

    # Energy and Smoothness
    ENERGY_PENALTY_SCALE = 0.005 # Standard penalty for action magnitude

    # Gait Cycle Components
    # Target values: double_support ~0.15, single_support ~0.65, flight ~0.0
    DOUBLE_SUPPORT_BONUS_WEIGHT = 0.8 # Significantly increased to encourage desired double support fraction
    FLIGHT_PENALTY_WEIGHT = 3.0 # Strong penalty to discourage flight

    # Joint Angle Targets for Human-like Gait (based on metric interpretation guide)
    KNEE_STANCE_STRAIGHT_TARGET_ANGLE = 0.3 # Max knee angle for 'straight' stance leg (<0.3 = straight)
    KNEE_STANCE_STRAIGHT_REWARD_SCALE = 1.0 # Reward for straight knee in stance

    HIP_SWING_FORWARD_MIN_ANGLE = 0.0 # Hip should be forward (+ angle) in swing phase
    HIP_SWING_FORWARD_REWARD_SCALE = 0.5 # Reward for hip moving forward in swing

    KNEE_SWING_BEND_MIN_ANGLE = 0.0 # Knee should bend (+ angle) in swing phase
    KNEE_SWING_BEND_REWARD_SCALE = 0.5 # Reward for knee bending in swing

    HIP_STANCE_BACK_MAX_ANGLE = -0.1 # Hip should not be too far back (< -0.1 rad) in stance
    HIP_STANCE_BACK_PENALTY_SCALE = 0.5 # Penalty for hip being too far back in stance

    DS_KNEE_BEND_TARGET_ANGLE = 0.2 # Slight knee bend in double support for shock absorption (e.g., 0.1-0.2 rad)
    DS_KNEE_BEND_REWARD_SCALE = 0.2 # Reward for knees being slightly bent during double support

    # Extracting observations
    hull_angle = obs[0]
    hull_angular_velocity = obs[1]
    x_velocity = obs[2]
    y_velocity = obs[3]

    right_hip_angle = obs[4]
    right_knee_angle = obs[6]
    right_contact_force = obs[8] # 0 = air, 1 = ground

    left_hip_angle = obs[9]
    left_knee_angle = obs[11]
    left_contact_force = obs[13] # 0 = air, 1 = ground

    reward = 0.0

    # 1. Survival Bonus (Implicitly helps eliminate falls)
    reward += SURVIVAL_BONUS

    # 2. Forward Progress
    reward += x_velocity * X_VELOCITY_WEIGHT

    # 3. Upright Posture and Stability
    # Reward for maintaining a slight forward lean (target 0.1 rad)
    hull_angle_error = np.abs(hull_angle - HULL_ANGLE_TARGET)
    reward += (HULL_ANGLE_TARGET - hull_angle_error) * HULL_ANGLE_PENALTY_SCALE

    # Penalize high angular velocity of hull (wobbling torso)
    reward -= np.abs(hull_angular_velocity) * HULL_ANGULAR_VELOCITY_PENALTY_SCALE

    # 4. Fall Prevention (strong penalty for falling downwards)
    if y_velocity < Y_VELOCITY_FALLING_THRESHOLD:
        reward += y_velocity * Y_VELOCITY_FALLING_PENALTY_SCALE # y_velocity is negative, so this adds a large negative reward

    # 5. Energy Efficiency (action magnitude penalty)
    reward -= np.sum(np.square(action)) * ENERGY_PENALTY_SCALE

    # 6. Human-like Gait Cycle and Hip-Knee Coordination
    # Use a small threshold for contact force to determine ground contact
    is_right_contact = right_contact_force > 0.1
    is_left_contact = left_contact_force > 0.1

    num_contacts = is_right_contact + is_left_contact

    if num_contacts == 2:  # Double Support Phase (both feet on ground)
        reward += DOUBLE_SUPPORT_BONUS_WEIGHT
        # Encourage slight knee bend in double support for shock absorption
        reward += max(0, DS_KNEE_BEND_TARGET_ANGLE - np.abs(right_knee_angle)) * DS_KNEE_BEND_REWARD_SCALE
        reward += max(0, DS_KNEE_BEND_TARGET_ANGLE - np.abs(left_knee_angle)) * DS_KNEE_BEND_REWARD_SCALE

    elif num_contacts == 1:  # Single Support Phase (one foot on ground, other swinging)
        # No general bonus for single support as it's currently too frequent.
        # Instead, focus on rewarding specific properties of swing/stance.
        if is_right_contact: # Right leg stance, Left leg swing
            # Right leg (stance): encourage straight knee
            reward += max(0, KNEE_STANCE_STRAIGHT_TARGET_ANGLE - np.abs(right_knee_angle)) * KNEE_STANCE_STRAIGHT_REWARD_SCALE
            # Right leg (stance): penalize hip being too far back
            reward -= max(0, HIP_STANCE_BACK_MAX_ANGLE - right_hip_angle) * HIP_STANCE_BACK_PENALTY_SCALE

            # Left leg (swing): encourage hip forward and knee bend
            reward += max(0, left_hip_angle - HIP_SWING_FORWARD_MIN_ANGLE) * HIP_SWING_FORWARD_REWARD_SCALE
            reward += max(0, left_knee_angle - KNEE_SWING_BEND_MIN_ANGLE) * KNEE_SWING_BEND_REWARD_SCALE
        else: # Left leg stance, Right leg swing
            # Left leg (stance): encourage straight knee
            reward += max(0, KNEE_STANCE_STRAIGHT_TARGET_ANGLE - np.abs(left_knee_angle)) * KNEE_STANCE_STRAIGHT_REWARD_SCALE
            # Left leg (stance): penalize hip being too far back
            reward -= max(0, HIP_STANCE_BACK_MAX_ANGLE - left_hip_angle) * HIP_STANCE_BACK_PENALTY_SCALE

            # Right leg (swing): encourage hip forward and knee bend
            reward += max(0, right_hip_angle - HIP_SWING_FORWARD_MIN_ANGLE) * HIP_SWING_FORWARD_REWARD_SCALE
            reward += max(0, right_knee_angle - KNEE_SWING_BEND_MIN_ANGLE) * KNEE_SWING_BEND_REWARD_SCALE
    
    else: # num_contacts == 0 (Flight Phase - both feet off ground)
        reward -= FLIGHT_PENALTY_WEIGHT # Strong penalty to achieve flight_fraction -> 0
        
    return float(reward)
