# Auto-generated by LLM — do not edit by hand.
# Modify llm/prompt_builder.py or logs/human_hint.txt to influence the next iteration.

import numpy as np

import numpy as np

def compute_reward(obs, action):
    # 1. Fast, stable forward walking (maximise forward speed).
    # Reward for positive forward velocity (obs[2]).
    forward_velocity_reward = obs[2]
    reward = 1.0 * forward_velocity_reward

    # 2. Upright posture (minimise hull tilt, avoid falling).
    # Penalize absolute hull angle (obs[0]). 0 = perfectly upright.
    # The current 100% fall rate indicates this is a critical component.
    hull_angle_penalty = -5.0 * np.abs(obs[0])
    reward += hull_angle_penalty

    # Penalize hull angular velocity (obs[1]) to reduce wobbling and improve stability.
    # High angular velocity often precedes a fall.
    hull_angular_velocity_penalty = -1.0 * np.abs(obs[1])
    reward += hull_angular_velocity_penalty

    # 3. Energy efficiency (penalise unnecessary large torques).
    # Penalize the sum of squared actions (torques).
    energy_penalty = -0.001 * np.sum(np.square(action))
    reward += energy_penalty

    # 4. Smooth locomotion (avoid jerky, oscillating movements).
    # Penalize high joint angular velocities (obs[5], obs[7], obs[10], obs[12]).
    joint_angular_velocities = np.array([obs[5], obs[7], obs[10], obs[12]])
    joint_angular_velocity_penalty = -0.01 * np.sum(np.abs(joint_angular_velocities))
    reward += joint_angular_velocity_penalty

    # Researcher hint: Human-like walking pattern (1 leg stance 1 leg swing and vice versa)
    # Encourage alternating single-leg support and penalize undesired contact states.
    leg1_contact = obs[8]
    leg2_contact = obs[13]

    # Reward for a proper single-leg stance (one leg on ground, one off).
    if (leg1_contact == 1 and leg2_contact == 0) or \
       (leg1_contact == 0 and leg2_contact == 1):
        reward += 0.3 # Small positive reward for the desired gait pattern

    # Strongly penalize if both legs are off the ground, as this often indicates a fall or an uncontrolled jump.
    if (leg1_contact == 0 and leg2_contact == 0):
        reward -= 5.0 # Very strong penalty to prevent the agent from losing all contact

    # Slightly penalize prolonged double support (both legs on the ground).
    # While brief double support is natural, we aim to prevent shuffling or static stance.
    # Given the 100% fall rate, this penalty is kept mild to prioritize any form of contact over no contact.
    if (leg1_contact == 1 and leg2_contact == 1):
        reward -= 0.05

    return float(reward)
