# Auto-generated by LLM — do not edit by hand.
# Modify llm/prompt_builder.py or logs/human_hint.txt to influence the next iteration.

import numpy as np

import numpy as np

def compute_reward(obs, action):
    # Observation unpacking
    hull_angle = obs[0]
    hull_angular_velocity = obs[1]
    forward_velocity = obs[2]
    vertical_velocity = obs[3]

    # Right leg (leg 1)
    right_hip_angle = obs[4]
    right_hip_angular_speed = obs[5]
    right_knee_angle = obs[6]
    right_knee_angular_speed = obs[7]
    right_foot_contact = obs[8]

    # Left leg (leg 2)
    left_hip_angle = obs[9]
    left_hip_angular_speed = obs[10]
    left_knee_angle = obs[11]
    left_knee_angular_speed = obs[12]
    left_foot_contact = obs[13]

    # --- Reward Weights ---
    W_FORWARD = 2.0         # Reward for moving forward
    W_UPRIGHT_ANGLE = 5.0   # Penalty for hull angle deviation from target
    W_UPRIGHT_ANG_VEL = 0.2 # Penalty for hull angular velocity (wobbling)
    W_VERTICAL_PENALTY = 5.0 # Strong penalty for negative vertical velocity (falling)
    W_ENERGY = 0.0005       # Penalty for action magnitudes (energy consumption)

    W_GAIT_SINGLE_SUPPORT = 1.5 # Reward for being in single support
    W_GAIT_FLIGHT_PENALTY = 10.0 # Heavy penalty for both feet off ground (not walking)
    W_GAIT_DOUBLE_SUPPORT = 0.2 # Reward for double support (current fraction is too low)

    W_STANCE_KNEE_BENT = 2.0 # Penalty for bent knee in stance leg
    W_SWING_HIP_SPEED = 0.2  # Reward for hip angular speed during swing (for ROM)
    W_SWING_KNEE_FLEXION_OPTIMAL = 0.5 # Reward for optimal knee flexion during swing
    W_SWING_HIP_KNEE_COORDINATION = 0.5 # Reward for hip and knee moving in opposite directions during swing

    # --- Target values / thresholds ---
    TARGET_HULL_ANGLE = 0.05 # Slight forward lean (rad, 0 = upright)
    OPTIMAL_KNEE_SWING_ANGLE = 0.5 # Rad (target bend during swing for clearance)
    MAX_KNEE_SWING_ANGLE = 1.5 # Rad (don't bend knee too much during swing)
    MIN_KNEE_SWING_ANGLE = 0.1 # Rad (don't straighten knee too much during swing)

    # Initialize reward
    reward = 0.0

    # --- 1. Forward Progress (Goal 3) ---
    reward += W_FORWARD * forward_velocity

    # --- 2. Posture & Stability (Goal 1 & 4) ---
    # Penalize deviation from target hull angle (slight forward lean)
    reward -= W_UPRIGHT_ANGLE * np.abs(hull_angle - TARGET_HULL_ANGLE)
    # Penalize hull angular velocity (wobbling)
    reward -= W_UPRIGHT_ANG_VEL * np.abs(hull_angular_velocity)
    # Strong penalty for negative vertical velocity (falling)
    reward -= W_VERTICAL_PENALTY * np.maximum(0.0, -vertical_velocity)

    # --- 3. Energy Efficiency (Goal 5) ---
    reward -= W_ENERGY * np.sum(np.square(action))

    # --- 4. Gait Cycle & Coordination (Goal 2 & 7) ---
    num_contacts = right_foot_contact + left_foot_contact

    # Prefer single support phase, reward some double support, heavily penalize flight
    if num_contacts == 1:
        reward += W_GAIT_SINGLE_SUPPORT
    elif num_contacts == 2: # Double support phase
        reward += W_GAIT_DOUBLE_SUPPORT # Reward double support, as its fraction is too low
    else: # num_contacts == 0 (Flight phase)
        reward -= W_GAIT_FLIGHT_PENALTY

    # Right Leg Specific Gait
    if right_foot_contact == 1: # Right leg in stance
        # Penalize bent knee in stance (target straight leg)
        reward -= W_STANCE_KNEE_BENT * np.abs(right_knee_angle) # obs[6] is + for bent
    else: # Right leg in swing
        # Reward hip angular speed for propulsion/range of motion
        reward += W_SWING_HIP_SPEED * np.abs(right_hip_angular_speed)
        # Reward for optimal knee flexion during swing for clearance
        knee_flexion_reward = -np.abs(right_knee_angle - OPTIMAL_KNEE_SWING_ANGLE)
        # Add a bonus if knee is within a reasonable range for swing
        if MIN_KNEE_SWING_ANGLE < right_knee_angle < MAX_KNEE_SWING_ANGLE:
             knee_flexion_reward += 0.2
        reward += W_SWING_KNEE_FLEXION_OPTIMAL * knee_flexion_reward
        # Reward hip-knee coordination (opposite movements, e.g., hip extend, knee flex)
        # Product of angular speeds is negative if moving in opposite directions.
        # np.maximum(0.0, ...) ensures we only reward positive coordination.
        reward += W_SWING_HIP_KNEE_COORDINATION * np.maximum(0.0, -right_hip_angular_speed * right_knee_angular_speed)

    # Left Leg Specific Gait (Symmetry is encouraged by identical rewards)
    if left_foot_contact == 1: # Left leg in stance
        # Penalize bent knee in stance (target straight leg)
        reward -= W_STANCE_KNEE_BENT * np.abs(left_knee_angle)
    else: # Left leg in swing
        # Reward hip angular speed for propulsion/range of motion
        reward += W_SWING_HIP_SPEED * np.abs(left_hip_angular_speed)
        # Reward for optimal knee flexion during swing for clearance
        knee_flexion_reward = -np.abs(left_knee_angle - OPTIMAL_KNEE_SWING_ANGLE)
        if MIN_KNEE_SWING_ANGLE < left_knee_angle < MAX_KNEE_SWING_ANGLE:
             knee_flexion_reward += 0.2
        reward += W_SWING_KNEE_FLEXION_OPTIMAL * knee_flexion_reward
        # Reward hip-knee coordination
        reward += W_SWING_HIP_KNEE_COORDINATION * np.maximum(0.0, -left_hip_angular_speed * left_knee_angular_speed)

    return float(reward)
