# Auto-generated by LLM — do not edit by hand.
# Modify llm/prompt_builder.py or logs/human_hint.txt to influence the next iteration.

import numpy as np

import numpy as np

def compute_reward(obs, action):
    # Observation indices for clarity and readability
    hull_angle = obs[0]
    hull_angular_velocity = obs[1]
    x_velocity = obs[2]
    # y_velocity = obs[3] # Vertical velocity is not directly rewarded/penalized for human-like walking goal
    right_hip_angle = obs[4]
    # right_hip_angular_speed = obs[5] # Not directly used for reward, but contributes to energy and stability
    right_knee_angle = obs[6]
    # right_knee_angular_speed = obs[7] # Not directly used for reward
    right_foot_contact = obs[8]
    left_hip_angle = obs[9]
    # left_hip_angular_speed = obs[10] # Not directly used for reward
    left_knee_angle = obs[11]
    # left_knee_angular_speed = obs[12] # Not directly used for reward
    left_foot_contact = obs[13]
    # lidar_readings = obs[14:] # LIDAR readings are for terrain, not directly for gait

    reward = 0.0

    # 1. Forward Progress (Goal 3) - Primary positive reward for locomotion
    # The agent is currently moving backward, so this needs to be a strong incentive.
    reward += x_velocity * 10.0 # Increased weighting for faster forward movement

    # 2. Upright Posture & Stability (Goal 4 & part of Goal 1 - Eliminate Falls)
    # Penalize large deviations from upright hull angle (0 radians).
    # Current torso_tilt (0.77 rad) is high, needs strong penalty.
    # Penalize hull angular velocity to reduce wobbling (current lateral_stability is okay, but can improve).
    # A slight forward lean is natural, but for stability, penalize strong deviations from 0.
    reward -= np.abs(hull_angle) * 5.0 # Strong penalty for torso tilt
    reward -= np.abs(hull_angular_velocity) * 0.2 # Penalty for torso angular velocity

    # 3. Energy Efficiency (Goal 5) & Action Smoothness (Goal 6)
    # Penalize the magnitude of actions (motor torques) to encourage energy efficiency.
    # This also indirectly promotes smoother actions.
    action_cost = np.sum(action**2)
    reward -= action_cost * 0.001 # Small penalty for energy consumption

    # 4. Human-like Gait Cycle (Goal 2 & part of Goal 1 - Eliminate Falls)
    # Reward specific foot contact patterns.
    is_right_foot_contact = right_foot_contact > 0.5
    is_left_foot_contact = left_foot_contact > 0.5

    single_support_right_stance = is_right_foot_contact and not is_left_foot_contact
    single_support_left_stance = is_left_foot_contact and not is_right_foot_contact
    double_support = is_right_foot_contact and is_left_foot_contact
    flight = not is_right_foot_contact and not is_left_foot_contact

    # Target: single_support_fraction ≈ 0.65, double_support_fraction ≈ 0.15, flight_fraction ≈ 0
    if single_support_right_stance or single_support_left_stance:
        reward += 1.0 # Significant reward for stable single-leg support
    
    if double_support:
        reward += 0.2 # Moderate reward for double support (brief transition phase)

    if flight:
        reward -= 2.0 # Heavy penalty for both feet off the ground (walking, not hopping)

    # 5. Hip & Knee Coordination and Stance/Swing Leg Configuration (Goal 7)
    # Encourage a straight stance leg and a flexed swing leg for ground clearance.

    # Right Leg Specifics
    if is_right_foot_contact: # Right leg is the STANCE leg
        # Encourage straight knee (right_knee_angle close to 0 radians)
        # Current stance_leg_straightness is 0.1388, which is good but could worsen. Keep it low.
        reward -= np.abs(right_knee_angle) * 1.0 # Strong penalty for bent stance knee
        
        # Encourage a neutral to slightly extended hip during stance for propulsion/stability.
        # Penalize excessive hip flexion (leg too far forward)
        # Hip angle 0.0 is straight down, positive is forward, negative is backward.
        reward -= np.clip(right_hip_angle - 0.1, 0, None) * 0.8 # Penalize hip forward past 0.1 rad
        reward += np.clip(0.05 - right_hip_angle, 0, None) * 0.2 # Small reward for hip being slightly back/neutral (<0.05)

    else: # Right leg is the SWING leg
        # Encourage knee flexion (positive right_knee_angle) for ground clearance.
        # The knee should bend, then extend for foot placement. Target positive angle.
        reward += np.clip(right_knee_angle - 0.2, 0, 1.5) * 0.5 # Reward knee flexion (e.g., 0.2 to 1.5 rad bent)
        # Penalize extreme knee angles (hyperextension or excessive flexion)
        reward -= np.clip(right_knee_angle - 1.5, 0, None) * 0.5 # Penalize too much flexion
        reward -= np.clip(-0.2 - right_knee_angle, 0, None) * 0.5 # Penalize hyperextension/too far back
        
        # Encourage hip flexion to bring the leg forward during swing.
        reward += np.clip(right_hip_angle, 0.1, 1.0) * 0.4 # Reward hip swinging forward (0.1 to 1.0 rad)
        # Penalize hip being too far back during swing phase
        reward -= np.clip(0.1 - right_hip_angle, 0, None) * 0.6 # Penalize if hip is not forward enough (<0.1 rad)

    # Left Leg Specifics (Symmetric to Right Leg)
    if is_left_foot_contact: # Left leg is the STANCE leg
        reward -= np.abs(left_knee_angle) * 1.0
        reward -= np.clip(left_hip_angle - 0.1, 0, None) * 0.8
        reward += np.clip(0.05 - left_hip_angle, 0, None) * 0.2

    else: # Left leg is the SWING leg
        reward += np.clip(left_knee_angle - 0.2, 0, 1.5) * 0.5
        reward -= np.clip(left_knee_angle - 1.5, 0, None) * 0.5
        reward -= np.clip(-0.2 - left_knee_angle, 0, None) * 0.5
        reward += np.clip(left_hip_angle, 0.1, 1.0) * 0.4
        reward -= np.clip(0.1 - left_hip_angle, 0, None) * 0.6

    return reward
