# Auto-generated by LLM — do not edit by hand.
# Modify llm/prompt_builder.py or logs/human_hint.txt to influence the next iteration.

import numpy as np

import numpy as np

def compute_reward(obs, action):
    # Constants for reward weighting
    W_FORWARD_VEL = 3.0             # Reward for forward movement (Priority 3)
    W_VERTICAL_VEL = 0.5            # Reward for maintaining height/vertical movement (helps prevent falls)
    W_POSTURE_HULL_ANGLE = 1.0      # Penalty for deviation from target hull angle (Priority 4)
    W_POSTURE_ANG_VEL = 0.5         # Penalty for high hull angular velocity (Priority 4)
    W_ENERGY_ABS = 0.05             # Penalty for action magnitude (sum of absolute torques) (Priority 5)

    # Gait Cycle Weights (Priority 2)
    W_PERFECT_SINGLE_SUPPORT = 1.5  # Strong reward for ideal single support
    W_EXCESSIVE_DOUBLE_SUPPORT = 1.0 # Penalty for too much double support
    W_FLIGHT_PENALTY = 2.0          # Strong penalty for flight (no feet on ground)

    # Leg Configuration Weights (Priority 2, 7)
    W_STANCE_HIP = 0.3
    W_STANCE_KNEE = 0.5
    W_SWING_HIP = 0.3
    W_SWING_KNEE_BEND_PENALTY = 0.4 # Penalty for swing knee out of ideal range

    # Target values for ideal posture and leg configurations
    TARGET_HULL_ANGLE = 0.1         # Slight forward lean (rad, 0 = upright)
    STANCE_HIP_TARGET = -0.2        # Stance leg hip slightly backward for propulsion (rad)
    STANCE_KNEE_TARGET = 0.0        # Stance leg knee straight (rad)
    SWING_HIP_TARGET = 0.8          # Swing leg hip well forward (rad)
    SWING_KNEE_MIN_BEND = 0.3       # Minimum bend for swing leg knee clearance (rad)
    SWING_KNEE_MAX_BEND = 1.0       # Maximum reasonable bend for swing leg knee (rad)

    # Observation parsing
    hull_angle = obs[0]
    hull_angular_vel = obs[1]
    forward_vel = obs[2]
    vertical_vel = obs[3]
    
    right_hip_angle = obs[4]
    # right_hip_angular_speed = obs[5] # Not used
    right_knee_angle = obs[6]
    # right_knee_angular_speed = obs[7] # Not used
    right_contact = obs[8]

    left_hip_angle = obs[9]
    # left_hip_angular_speed = obs[10] # Not used
    left_knee_angle = obs[11]
    # left_knee_angular_speed = obs[12] # Not used
    left_contact = obs[13]

    # --- Reward Components ---

    # 1. Forward Progress (Priority 3)
    reward_forward = forward_vel * W_FORWARD_VEL

    # 2. Prevent Sinking / Help with fall recovery (Part of Priority 1)
    # Positive vertical velocity is good, negative means sinking/falling.
    reward_vertical_vel = vertical_vel * W_VERTICAL_VEL

    # 3. Upright Posture (Priority 4)
    reward_posture_angle = -np.abs(hull_angle - TARGET_HULL_ANGLE) * W_POSTURE_HULL_ANGLE
    reward_posture_angular_vel = -np.abs(hull_angular_vel) * W_POSTURE_ANG_VEL

    # 4. Energy Efficiency (Priority 5)
    # Using sum of absolute torques to align with `energy_consumption` metric.
    reward_energy = -np.sum(np.abs(action)) * W_ENERGY_ABS

    # 5. Gait Cycle & Leg Configuration (Priority 2 & 7)
    reward_gait_cycle_contact = 0.0
    reward_leg_config = 0.0

    is_right_single_support = (right_contact == 1 and left_contact == 0)
    is_left_single_support = (right_contact == 0 and left_contact == 1)
    is_double_support = (right_contact == 1 and left_contact == 1)
    is_flight = (right_contact == 0 and left_contact == 0)

    # Reward for alternating single support (key for human-like gait)
    if is_right_single_support or is_left_single_support:
        reward_gait_cycle_contact += W_PERFECT_SINGLE_SUPPORT
    
    # Penalty for double support (current metric is too high)
    if is_double_support:
        reward_gait_cycle_contact -= W_EXCESSIVE_DOUBLE_SUPPORT

    # Penalty for flight (walking, not hopping or falling)
    if is_flight:
        reward_gait_cycle_contact -= W_FLIGHT_PENALTY

    # Reward for stance leg configuration (straight knee, propulsive hip)
    if right_contact == 1: # Right leg is stance
        reward_leg_config += -np.abs(right_hip_angle - STANCE_HIP_TARGET) * W_STANCE_HIP
        reward_leg_config += -np.abs(right_knee_angle - STANCE_KNEE_TARGET) * W_STANCE_KNEE
    if left_contact == 1: # Left leg is stance
        reward_leg_config += -np.abs(left_hip_angle - STANCE_HIP_TARGET) * W_STANCE_HIP
        reward_leg_config += -np.abs(left_knee_angle - STANCE_KNEE_TARGET) * W_STANCE_KNEE

    # Reward/Penalty for swing leg configuration (forward hip, knee bent within range)
    if right_contact == 0: # Right leg is swing
        reward_leg_config += -np.abs(right_hip_angle - SWING_HIP_TARGET) * W_SWING_HIP
        # Penalize if swing knee is too straight or too bent
        if right_knee_angle < SWING_KNEE_MIN_BEND:
            reward_leg_config -= (SWING_KNEE_MIN_BEND - right_knee_angle) * W_SWING_KNEE_BEND_PENALTY
        elif right_knee_angle > SWING_KNEE_MAX_BEND:
            reward_leg_config -= (right_knee_angle - SWING_KNEE_MAX_BEND) * W_SWING_KNEE_BEND_PENALTY
        # (Implicitly rewarded for being within range by not being penalized)

    if left_contact == 0: # Left leg is swing
        reward_leg_config += -np.abs(left_hip_angle - SWING_HIP_TARGET) * W_SWING_HIP
        # Penalize if swing knee is too straight or too bent
        if left_knee_angle < SWING_KNEE_MIN_BEND:
            reward_leg_config -= (SWING_KNEE_MIN_BEND - left_knee_angle) * W_SWING_KNEE_BEND_PENALTY
        elif left_knee_angle > SWING_KNEE_MAX_BEND:
            reward_leg_config -= (left_knee_angle - SWING_KNEE_MAX_BEND) * W_SWING_KNEE_BEND_PENALTY
        # (Implicitly rewarded for being within range by not being penalized)

    # Total reward calculation
    total_reward = (
        reward_forward
        + reward_vertical_vel
        + reward_posture_angle
        + reward_posture_angular_vel
        + reward_energy
        + reward_gait_cycle_contact
        + reward_leg_config
    )
    
    return float(total_reward)
