# Auto-generated by LLM — do not edit by hand.
# Modify llm/prompt_builder.py or logs/human_hint.txt to influence the next iteration.

import numpy as np

import numpy as np

def compute_reward(obs, action):
    # Constants for weights, adjusted based on performance metrics and goals
    W_FORWARD_VEL = 6.0  # Increased for stronger forward progress
    W_FORWARD_VEL_NEGATIVE_PENALTY = 15.0 # Heavy penalty for moving backward

    # Posture and Stability
    TARGET_HULL_ANGLE = 0.08  # Slight forward lean (0.05-0.15 rad)
    W_HULL_TILT_PENALTY = 3.0 # Increased to refine torso tilt
    W_HULL_ANG_VEL_PENALTY = 0.8 # Increased for better stability
    W_VERTICAL_VEL_PENALTY = 0.2 # Small penalty for excessive vertical motion

    # Gait Cycle Components - CRITICAL FOR HUMAN-LIKE WALKING
    W_SINGLE_SUPPORT_REWARD = 1.2 # Strong reward for single support phase
    W_DOUBLE_SUPPORT_PENALTY = 2.0 # Increased penalty to reduce double support fraction (target 0.15)
    W_FLIGHT_PENALTY = 8.0 # Very heavy penalty for both feet off ground (target 0.0)

    # Hip & Knee Coordination
    W_STANCE_KNEE_STRAIGHTNESS_PENALTY = 1.0 # Penalize bent knee in stance
    W_SWING_KNEE_BENT_REWARD = 0.4 # Reward bent knee during swing for clearance
    W_SWING_HIP_FORWARD_REWARD = 0.3 # Reward hip forward during swing for propulsion
    W_STANCE_HIP_EXTEND_REWARD = 0.3 # Reward hip extended during stance for push-off

    # Energy Efficiency & Smoothness
    W_ENERGY_PENALTY = 0.007 # Slightly increased to reduce energy consumption and promote smoothness

    # Unpack observations for readability
    hull_angle = obs[0]
    hull_angular_velocity = obs[1]
    forward_vel = obs[2]
    vertical_vel = obs[3]

    hip_r_angle = obs[4]
    # hip_r_speed = obs[5] # Not used directly in this iteration
    knee_r_angle = obs[6]
    # knee_r_speed = obs[7] # Not used directly in this iteration
    contact_r = obs[8]

    hip_l_angle = obs[9]
    # hip_l_speed = obs[10] # Not used directly in this iteration
    knee_l_angle = obs[11]
    # knee_l_speed = obs[12] # Not used directly in this iteration
    contact_l = obs[13]

    reward = 0.0

    # 1. Forward Progress (Goal 3)
    reward_forward = forward_vel * W_FORWARD_VEL
    if forward_vel < 0:
        reward_forward += forward_vel * W_FORWARD_VEL_NEGATIVE_PENALTY # Additional heavy penalty for backward movement
    reward += reward_forward

    # 2. Upright Posture & Stability (Goal 4)
    # Penalize deviation from target hull angle (slight forward lean)
    reward_hull_tilt = -np.abs(hull_angle - TARGET_HULL_ANGLE) * W_HULL_TILT_PENALTY
    reward_hull_angular_vel = -np.abs(hull_angular_velocity) * W_HULL_ANG_VEL_PENALTY
    reward_vertical_vel = -np.abs(vertical_vel) * W_VERTICAL_VEL_PENALTY # Penalize excessive vertical motion for smoother gait
    reward += reward_hull_tilt + reward_hull_angular_vel + reward_vertical_vel

    # Goal 1: ELIMINATE FALLS (primary safeguard)
    # Heavy penalty for severe backward lean, which often precedes a fall
    if hull_angle < -0.4:
        reward -= 20.0 # Significantly increased penalty

    # 3. Human-like Gait Cycle (Goal 2)
    # Use a threshold for contact robustness (gym contact values can be noisy)
    is_contact_r = contact_r > 0.1
    is_contact_l = contact_l > 0.1

    # Single support phase: one leg on ground, the other in air (ideal for walking)
    single_support = (is_contact_r != is_contact_l)
    reward += single_support * W_SINGLE_SUPPORT_REWARD

    # Double support phase: both legs on ground. Penalize more to reduce its fraction towards ~0.15.
    double_support = (is_contact_r and is_contact_l)
    reward -= double_support * W_DOUBLE_SUPPORT_PENALTY

    # Flight phase: both legs in air. Heavily penalize as we want walking, not hopping/running.
    flight = (not is_contact_r and not is_contact_l)
    reward -= flight * W_FLIGHT_PENALTY

    # 4. Hip & Knee Coordination (Goal 7)
    # Right Leg kinematics
    if is_contact_r: # Right leg is in stance phase
        # Encourage straight knee in stance for efficiency
        reward -= np.abs(knee_r_angle) * W_STANCE_KNEE_STRAIGHTNESS_PENALTY
        # Encourage hip extension for push-off in late stance (hip angle should be negative)
        reward += np.maximum(0, -hip_r_angle) * W_STANCE_HIP_EXTEND_REWARD
    else: # Right leg is in swing phase
        # Encourage knee flexion for foot clearance (knee angle should be positive)
        reward += np.maximum(0, knee_r_angle) * W_SWING_KNEE_BENT_REWARD
        # Encourage hip flexion to swing leg forward (hip angle should be positive)
        reward += np.maximum(0, hip_r_angle) * W_SWING_HIP_FORWARD_REWARD

    # Left Leg kinematics (symmetric rewards)
    if is_contact_l: # Left leg is in stance phase
        # Encourage straight knee in stance
        reward -= np.abs(knee_l_angle) * W_STANCE_KNEE_STRAIGHTNESS_PENALTY
        # Encourage hip extension for push-off
        reward += np.maximum(0, -hip_l_angle) * W_STANCE_HIP_EXTEND_REWARD
    else: # Left leg is in swing phase
        # Encourage knee flexion for foot clearance
        reward += np.maximum(0, knee_l_angle) * W_SWING_KNEE_BENT_REWARD
        # Encourage hip flexion to swing leg forward
        reward += np.maximum(0, hip_l_angle) * W_SWING_HIP_FORWARD_REWARD

    # 5. Energy Efficiency & Smooth Actions (Goals 5 & 6)
    # Penalize the absolute value of torques (actions)
    reward_energy_penalty = -np.sum(np.abs(action)) * W_ENERGY_PENALTY
    reward += reward_energy_penalty

    return reward
