# Auto-generated by LLM — do not edit by hand.
# Modify llm/prompt_builder.py or logs/human_hint.txt to influence the next iteration.

import numpy as np

import numpy as np

def compute_reward(obs, action):
    # Unpack observations for readability
    hull_angle = obs[0]                 # Torso angle (rad, 0 = upright, + = forward lean)
    hull_angular_velocity = obs[1]      # Torso angular velocity (+ = tilting forward)
    forward_velocity = obs[2]           # Horizontal velocity (normalised m/s)
    vertical_velocity = obs[3]          # Vertical velocity
    right_knee_angle = obs[6]           # Right knee angle (+ = bent)
    right_foot_contact = obs[8]         # Right foot contact (0 = air, 1 = ground)
    left_knee_angle = obs[11]           # Left knee angle (+ = bent)
    left_foot_contact = obs[13]         # Left foot contact (0 = air, 1 = ground)

    reward = 0.0

    # --- 1. ELIMINATE FALLS (Highest Priority) ---
    # This involves encouraging stability, upright posture, and penalizing significant drops.

    # 1.1. Base survival reward: Encourages the agent to stay alive
    reward += 1.0

    # 1.2. Posture Stability: Encourage a stable, slightly forward-leaning posture.
    # Ideal torso tilt is around 0.1 rad (5-15 degrees forward lean).
    target_hull_angle = 0.1
    reward -= 5.0 * np.abs(hull_angle - target_hull_angle) # Heavy penalty for deviations

    # Penalize large hull angular velocity (wobbling)
    reward -= 1.0 * np.abs(hull_angular_velocity)

    # 1.3. Vertical Stability: Strongly penalize negative vertical velocity, indicating a fall.
    if vertical_velocity < -0.1: # Significant drop
        reward -= 15.0 * np.abs(vertical_velocity) # Very heavy penalty for rapid falls
    elif vertical_velocity < 0: # Moderate drop
        reward -= 2.0 * np.abs(vertical_velocity)  # Moderate penalty for losing altitude


    # --- 2. ACHIEVE HUMAN-LIKE GAIT CYCLE (High Priority) ---

    # Determine contact states
    is_right_stance = (right_foot_contact == 1)
    is_left_stance = (left_foot_contact == 1)

    is_single_support = (is_right_stance and not is_left_stance) or (is_left_stance and not is_right_stance)
    is_double_support = (is_right_stance and is_left_stance)
    is_flight = (not is_right_stance and not is_left_stance)

    # 2.1. Single Support: Strong reward for the desired walking phase.
    if is_single_support:
        reward += 5.0

    # 2.2. Double Support: Reward briefly for transitions, but penalize if stationary.
    # Target double_support_fraction ≈ 0.15
    if is_double_support:
        # Only reward if moving forward, to prevent standing still with both feet.
        if forward_velocity > 0.05: # Minimum forward velocity to count as progressive double support
            reward += 1.5
        else:
            reward -= 3.0 # Penalize standing or shuffling without progress

    # 2.3. Flight Phase: Strongly penalize both feet off the ground (hopping/running).
    # Target flight_fraction ≈ 0
    if is_flight:
        reward -= 10.0 # Very high penalty for losing ground contact

    # 2.4. Stance Leg Straightness: Encourage efficient, near-straight knee in stance.
    # Target stance_leg_straightness < 0.3 (knee angle close to 0 when on ground).
    stance_knee_penalty_magnitude = 2.0
    if is_right_stance:
        reward -= stance_knee_penalty_magnitude * np.abs(right_knee_angle)
    if is_left_stance:
        reward -= stance_knee_penalty_magnitude * np.abs(left_knee_angle)


    # --- 3. FORWARD PROGRESS (Medium-High Priority) ---
    # Target average_speed ↑ (e.g., 0.05-0.15 normalised m/s)

    # Reward for positive forward velocity
    reward += 3.0 * forward_velocity

    # Penalize moving backward more heavily than moving forward.
    if forward_velocity < 0:
        reward += 10.0 * forward_velocity # `forward_velocity` is negative, so this is a penalty
    elif forward_velocity < 0.05:
        # Small penalty for very slow forward motion to encourage a brisk walk.
        reward -= 0.5


    # --- 4. ENERGY EFFICIENCY & SMOOTHNESS (Medium Priority) ---
    # Target energy_consumption ↓ and action_smoothness ↓

    # Penalize the sum of squared motor torques (actions) to encourage energy efficiency and smoother movements.
    # Actions are in [-1, 1], so squaring makes them positive [0, 1].
    energy_penalty_magnitude = 0.0002
    reward -= energy_penalty_magnitude * np.sum(action**2)

    return reward
