# Auto-generated by LLM — do not edit by hand.
# Modify llm/prompt_builder.py or logs/human_hint.txt to influence the next iteration.

import numpy as np

import numpy as np

def compute_reward(obs, action):
    # Unpack observations for clarity and easy access
    hull_angle = obs[0]
    hull_angular_velocity = obs[1]
    forward_velocity = obs[2]
    # vertical_velocity = obs[3] # Not directly used for reward but contributes to stability

    right_hip_angle = obs[4]
    right_hip_speed = obs[5]
    right_knee_angle = obs[6]
    right_knee_speed = obs[7]
    right_contact = obs[8] # 0 = air, 1 = ground

    left_hip_angle = obs[9]
    left_hip_speed = obs[10]
    left_knee_angle = obs[11]
    left_knee_speed = obs[12]
    left_contact = obs[13] # 0 = air, 1 = ground

    # --- 1. Base Reward: Forward Progress (Goal 3) ---
    # Primary reward for moving forward. Increased weight.
    reward = forward_velocity * 2.5

    # --- 2. Penalize Falling & Maintain Upright Posture (Goal 1, 4) ---
    # Hull angle penalty: Heavily penalize large deviations from a slightly forward-leaning posture.
    # Ideal human posture has a slight forward lean.
    ideal_hull_angle = 0.1 # rad, slight forward lean for efficiency
    posture_penalty = np.abs(hull_angle - ideal_hull_angle) * 3.0
    reward -= posture_penalty

    # Hull angular velocity penalty: Penalize wobbling (instability).
    stability_penalty = np.abs(hull_angular_velocity) * 0.2
    reward -= stability_penalty

    # Heavy penalty if very close to falling (hull angle threshold is 0.5 rad for termination)
    # This helps eliminate falls by penalizing states just before termination.
    if np.abs(hull_angle) > 0.4:
        reward -= (np.abs(hull_angle) - 0.4) * 20.0 # Stronger penalty to aggressively prevent falls

    # --- 3. Energy Efficiency (Goal 5) & Smooth Actions (Goal 6) ---
    # Penalize the magnitude of actions (torque squared) to encourage efficiency and smoothness.
    action_cost = np.sum(np.square(action)) * 0.01 # Increased weight slightly for better action smoothness
    reward -= action_cost

    # --- 4. Human-like Gait Cycle & Coordination (Goal 2, 7) ---
    gait_reward = 0.0

    # Determine gait phases based on foot contact
    # Use a small threshold as contact can be slightly fuzzy in continuous physics engines
    contact_threshold = 0.1
    is_right_grounded = right_contact > contact_threshold
    is_left_grounded = left_contact > contact_threshold

    is_flight = (~is_right_grounded) * (~is_left_grounded)
    is_double_support = is_right_grounded * is_left_grounded
    is_right_stance = is_right_grounded * (~is_left_grounded)
    is_left_stance = is_left_grounded * (~is_right_grounded)

    # Penalize flight phase heavily (Goal 2: flight_fraction ~ 0)
    if is_flight:
        gait_reward -= 15.0 # Very heavy penalty for being airborne, promotes walking over hopping

    # Reward single support (Goal 2: single_support_fraction ~ 0.65)
    if is_right_stance or is_left_stance:
        gait_reward += 2.0 # Stronger reward for single support phase

    # Moderately reward double support (Goal 2: double_support_fraction ~ 0.15)
    # This helps transitions and provides stability without encouraging shuffling.
    if is_double_support:
        gait_reward += 0.5

    # Stance leg mechanics: Straight knee, hip extension for propulsion (Goal 7)
    # Penalize bent knees during stance phase, reward hip extension for powerful push-off.
    if is_right_stance:
        gait_reward -= np.abs(right_knee_angle) * 2.0  # Penalize bent right knee in stance
        gait_reward += np.maximum(0, -right_hip_angle - 0.1) * 0.7 # Reward hip extension (negative angle) for push-off
    if is_left_stance:
        gait_reward -= np.abs(left_knee_angle) * 2.0   # Penalize bent left knee in stance
        gait_reward += np.maximum(0, -left_hip_angle - 0.1) * 0.7 # Reward hip extension for push-off

    # Swing leg mechanics: Hip flexion, knee flexion for clearance (Goal 7)
    # When one leg is in stance, the other should be swinging, demonstrating coordinated movement.
    if is_left_stance and not is_right_stance: # Left stance, Right swing
        gait_reward += np.maximum(0, right_hip_angle) * 0.4    # Right hip forward (flexion)
        gait_reward += np.maximum(0, right_knee_angle - 0.3) * 0.4 # Right knee bent (flexion), target ~0.3 rad for clearance
        gait_reward -= (right_knee_angle > 1.2) * 0.5 # Penalize excessive knee bending during swing

    if is_right_stance and not is_left_stance: # Right stance, Left swing
        gait_reward += np.maximum(0, left_hip_angle) * 0.4     # Left hip forward (flexion)
        gait_reward += np.maximum(0, left_knee_angle - 0.3) * 0.4  # Left knee bent (flexion), target ~0.3 rad for clearance
        gait_reward -= (left_knee_angle > 1.2) * 0.5 # Penalize excessive knee bending during swing

    # Gait Symmetry: Encourage alternating pattern. (Goal 2: gait_symmetry_index -> 0)
    # Discourage both legs trying to do the same thing (e.g., both hips forward or both hips back)
    # This helps enforce a distinct alternating swing/stance pattern.
    symmetry_penalty = 0.0
    # Penalize if both hips are significantly forward (not alternating)
    symmetry_penalty += np.maximum(0, right_hip_angle - 0.3) * np.maximum(0, left_hip_angle - 0.3) * 0.5
    # Penalize if both hips are significantly backward (not alternating)
    symmetry_penalty += np.maximum(0, -right_hip_angle - 0.3) * np.maximum(0, -left_hip_angle - 0.3) * 0.5
    gait_reward -= symmetry_penalty

    # Final reward calculation
    reward += gait_reward

    return reward
