# Auto-generated by LLM — do not edit by hand.
# Modify llm/prompt_builder.py or logs/human_hint.txt to influence the next iteration.

import numpy as np

import numpy as np

def compute_reward(obs, action):
    # Observation indices for clarity
    hull_angle = obs[0]                 # Torso angle (rad, 0 = upright)
    hull_angular_velocity = obs[1]      # Torso angular velocity
    forward_velocity = obs[2]           # Forward (x) velocity
    # vertical_velocity = obs[3]        # Vertical (y) velocity
    right_hip_angle = obs[4]
    # right_hip_angular_speed = obs[5]
    right_knee_angle = obs[6]
    # right_knee_angular_speed = obs[7]
    right_foot_contact = obs[8]         # Right foot ground contact (0 = air, 1 = ground)
    left_hip_angle = obs[9]
    # left_hip_angular_speed = obs[10]
    left_knee_angle = obs[11]
    # left_knee_angular_speed = obs[12]
    left_foot_contact = obs[13]         # Left foot ground contact (0 = air, 1 = ground)

    # Reward component weights
    FORWARD_VELOCITY_WEIGHT = 4.0
    HULL_ANGLE_PENALTY_WEIGHT = 8.0
    HULL_ANGULAR_VELOCITY_PENALTY_WEIGHT = 0.8
    ACTION_COST_WEIGHT = 0.0005
    FLIGHT_PENALTY = 15.0
    SINGLE_SUPPORT_REWARD = 2.5
    DOUBLE_SUPPORT_REWARD = 1.2
    STANCE_KNEE_BEND_PENALTY_WEIGHT = 4.0

    # Target values
    UPRIGHT_HULL_ANGLE_TARGET = 0.05  # Slight forward lean (0.05-0.15 rad is good)
    STANCE_KNEE_STRAIGHT_TARGET = 0.0 # Aim for straight knee during stance

    reward = 0.0

    # 1. ELIMINATE FALLS & UPRIGHT POSTURE (Priority 1 & 4)
    # Penalize deviation from target hull angle
    reward -= HULL_ANGLE_PENALTY_WEIGHT * abs(hull_angle - UPRIGHT_HULL_ANGLE_TARGET)
    # Penalize excessive hull angular velocity
    reward -= HULL_ANGULAR_VELOCITY_PENALTY_WEIGHT * abs(hull_angular_velocity)

    # Aggressive penalty for critical instability (robot falls 100% of the time)
    if abs(hull_angle) > 0.8 or abs(hull_angular_velocity) > 1.2:
        reward -= 50.0  # Very severe additional penalty to prevent falls

    # 2. FORWARD PROGRESS (Priority 3)
    reward += FORWARD_VELOCITY_WEIGHT * forward_velocity
    # Strong penalty for moving backward
    if forward_velocity < 0:
        reward -= 8.0 * abs(forward_velocity)
    # Penalty for very slow movement or stalling
    elif forward_velocity < 0.05:
        reward -= 3.0 * (0.05 - forward_velocity)

    # 3. ENERGY EFFICIENCY & SMOOTH ACTIONS (Priority 5 & 6)
    # Penalize the magnitude of actions to encourage energy efficiency and smoothness
    reward -= ACTION_COST_WEIGHT * np.sum(np.square(action))

    # 4. ACHIEVE HUMAN-LIKE GAIT CYCLE (Priority 2)
    is_right_foot_contact = (right_foot_contact > 0.1) # Threshold for contact sensor
    is_left_foot_contact = (left_foot_contact > 0.1)

    # Penalize flight phase (both feet off ground) very heavily (flight_fraction ≈ 0 for walking)
    if not is_right_foot_contact and not is_left_foot_contact:
        reward -= FLIGHT_PENALTY

    # Reward single support phase (one foot on ground, other swinging)
    # Target single_support_fraction ≈ 0.65
    if is_right_foot_contact and not is_left_foot_contact: # Right leg stance, Left leg swing
        reward += SINGLE_SUPPORT_REWARD
        # Encourage proper hip/knee angles for left leg swing
        reward += 0.5 * np.maximum(0, left_hip_angle)   # Reward hip flexion (forward swing)
        reward += 0.2 * np.maximum(0, left_knee_angle)  # Reward knee flexion (for clearance)
        if left_knee_angle < -0.2: # Penalize knee hyperextension during swing
            reward -= 1.0

    elif is_left_foot_contact and not is_right_foot_contact: # Left leg stance, Right leg swing
        # BOOST reward for right leg swing to improve gait symmetry (right_leg_swing_freq is too low)
        reward += SINGLE_SUPPORT_REWARD * 1.5
        # Encourage proper hip/knee angles for right leg swing
        reward += 0.5 * np.maximum(0, right_hip_angle)  # Reward hip flexion
        reward += 0.2 * np.maximum(0, right_knee_angle) # Reward knee flexion
        if right_knee_angle < -0.2: # Penalize knee hyperextension during swing
            reward -= 1.0

    # Reward double support phase (both feet on ground)
    # Target double_support_fraction ≈ 0.15
    if is_right_foot_contact and is_left_foot_contact:
        reward += DOUBLE_SUPPORT_REWARD

    # 5. STANCE LEG STRAIGHTNESS (Priority 7, important for efficient gait)
    # Penalize bent knees when the foot is on the ground (stance_leg_straightness < 0.3 is good)
    if is_right_foot_contact:
        reward -= STANCE_KNEE_BEND_PENALTY_WEIGHT * (right_knee_angle - STANCE_KNEE_STRAIGHT_TARGET)**2
    if is_left_foot_contact:
        reward -= STANCE_KNEE_BEND_PENALTY_WEIGHT * (left_knee_angle - STANCE_KNEE_STRAIGHT_TARGET)**2

    return float(reward)
