# Auto-generated by LLM — do not edit by hand.
# Modify llm/prompt_builder.py or logs/human_hint.txt to influence the next iteration.

import numpy as np

import numpy as np

def compute_reward(obs, action):
    # --- Reward Weights and Target Values ---
    # Primary objective: Forward velocity. Increased weight to encourage faster movement.
    WEIGHT_FORWARD_VEL = 2.5

    # Posture and Stability (High Priority: ELIMINATE FALLS, UPRIGHT POSTURE)
    # Hull angle deviation from upright (0 radians). Strong quadratic penalty to prevent falls.
    WEIGHT_HULL_ANGLE_PENALTY = 15.0
    # Hull angular velocity. Strong quadratic penalty to maintain stability.
    WEIGHT_HULL_ANG_VEL_PENALTY = 1.5

    # Energy Efficiency
    # Standard penalty for torque expenditure (energy consumption).
    WEIGHT_TORQUE_PENALTY = 0.0001

    # Gait Cycle (High Priority: Human-like walking)
    # Penalty for both feet off the ground (flight phase), to encourage walking over hopping.
    WEIGHT_FLIGHT_PENALTY = 0.8
    # Reward for being in single support phase.
    WEIGHT_SINGLE_SUPPORT_REWARD = 0.05
    # Reward for being in double support phase. Made higher to increase its frequency (current 0.09, goal ~0.15).
    WEIGHT_DOUBLE_SUPPORT_REWARD = 0.2

    # Stance Leg Straightness
    # Penalty for bent knee in the stance leg. A small bend (e.g., 0.1 rad) is natural.
    WEIGHT_STANCE_KNEE_BEND_PENALTY = 0.2
    TARGET_STANCE_KNEE_BEND = 0.1 # Slight knee bend in stance (rad)

    # --- Observation Extraction ---
    hull_angle = obs[0]             # Torso angle (0 = upright)
    hull_angular_velocity = obs[1]  # Torso angular velocity
    forward_velocity = obs[2]       # Horizontal velocity (main progress metric)
    right_knee_angle = obs[6]       # Right knee joint angle (+ = bent)
    right_contact = obs[8]          # Right foot ground contact (0 = air, 1 = ground)
    left_knee_angle = obs[11]       # Left knee joint angle (+ = bent)
    left_contact = obs[13]          # Left foot ground contact (0 = air, 1 = ground)

    # --- Initialize Reward ---
    reward = 0.0

    # 1. Forward Progress
    # Reward the agent for moving forward. This is the primary driving force.
    reward += WEIGHT_FORWARD_VEL * forward_velocity

    # 2. Posture and Stability (ELIMINATE FALLS, UPRIGHT POSTURE)
    # The fall_rate is 100%, indicating instability. Very strong penalties for deviation from upright.
    # Penalize deviation from upright hull angle (0 radians). Quadratic penalty hits extreme angles hard.
    reward -= WEIGHT_HULL_ANGLE_PENALTY * np.square(hull_angle)
    # Penalize hull angular velocity. Quadratic penalty for quick stabilization.
    reward -= WEIGHT_HULL_ANG_VEL_PENALTY * np.square(hull_angular_velocity)

    # 3. Energy Efficiency
    # Penalize the sum of squared action magnitudes (torques).
    reward -= WEIGHT_TORQUE_PENALTY * np.sum(np.square(action))

    # 4. Gait Cycle (Human-like walking)
    # Determine current contact states
    is_right_contact = right_contact > 0.1
    is_left_contact = left_contact > 0.1

    is_single_support = (is_right_contact and not is_left_contact) or (not is_right_contact and is_left_contact)
    is_double_support = (is_right_contact and is_left_contact)
    is_flight = (not is_right_contact and not is_left_contact)

    # Penalize flight phase to encourage walking (flight_fraction is already low, but reinforce this).
    reward -= WEIGHT_FLIGHT_PENALTY * is_flight

    # Reward for being in single support.
    reward += WEIGHT_SINGLE_SUPPORT_REWARD * is_single_support

    # Reward for being in double support. Increased weight to push 'double_support_fraction' towards target.
    reward += WEIGHT_DOUBLE_SUPPORT_REWARD * is_double_support

    # 5. Stance Leg Straightness
    # Penalize the knee bending for the leg that is currently in contact with the ground (stance leg).
    # A small positive target bend is allowed for natural gait.
    if is_right_contact:
        reward -= WEIGHT_STANCE_KNEE_BEND_PENALTY * np.abs(right_knee_angle - TARGET_STANCE_KNEE_BEND)
    if is_left_contact:
        reward -= WEIGHT_STANCE_KNEE_BEND_PENALTY * np.abs(left_knee_angle - TARGET_STANCE_KNEE_BEND)

    return float(reward)
