# Auto-generated by LLM — do not edit by hand.
# Modify llm/prompt_builder.py or logs/human_hint.txt to influence the next iteration.

import numpy as np

import numpy as np

def compute_reward(obs, action):
    # Unpack observations for readability
    hull_angle = obs[0]
    hull_angular_velocity = obs[1]
    forward_velocity = obs[2]
    vertical_velocity = obs[3]

    hip_1_angle = obs[4]
    # hip_1_angular_speed = obs[5]
    knee_1_angle = obs[6]
    # knee_1_angular_speed = obs[7]
    leg_1_contact = obs[8]  # Right foot (0 = air, 1 = ground)

    hip_2_angle = obs[9]
    # hip_2_angular_speed = obs[10]
    knee_2_angle = obs[11]
    # knee_2_angular_speed = obs[12]
    leg_2_contact = obs[13] # Left foot (0 = air, 1 = ground)

    # --- 1. Base forward progress reward ---
    # Primary goal is to move forward. This is the main driving reward.
    reward = 1.0 * forward_velocity

    # --- 2. Energy penalty (using squared actions for smoother control) ---
    # Current energy_consumption is high and worsening. action_smoothness is also worsening.
    # Increase penalty slightly from the default BipedalWalker-v3 environment's 0.0005.
    energy_penalty = -0.0008 * np.sum(np.square(action))
    reward += energy_penalty

    # --- 3. Torso Posture Reward/Penalty ---
    # Current torso_tilt (0.0622 rad) is good, aiming for a slight forward lean (0.05-0.15 rad).
    # Penalize deviation from a target forward lean of 0.1 rad.
    target_hull_angle = 0.1
    torso_tilt_penalty = -0.5 * (hull_angle - target_hull_angle)**2
    reward += torso_tilt_penalty

    # --- 4. Gait Cycle - Penalize Flight (both feet off ground) ---
    # flight_fraction (0.016) is slightly high, goal is 0.0 for walking (not hopping).
    # Use a small threshold (0.1) for ground contact to handle floating point noise.
    is_right_foot_in_air = leg_1_contact < 0.1
    is_left_foot_in_air = leg_2_contact < 0.1
    
    if is_right_foot_in_air and is_left_foot_in_air:
        reward -= 0.5 # Strong penalty for both feet off ground

    # --- 5. Stance Leg Straightness Penalty ---
    # stance_leg_straightness (0.0674) is good, maintain this by penalizing bent knees in stance.
    # A straight leg in stance is more energy-efficient.
    stance_knee_penalty = 0.0
    if not is_right_foot_in_air: # Right leg is in stance
        stance_knee_penalty += abs(knee_1_angle)
    if not is_left_foot_in_air: # Left leg is in stance
        stance_knee_penalty += abs(knee_2_angle)
    
    reward -= 0.2 * stance_knee_penalty

    # --- 6. Swing Leg Hip Movement Reward ---
    # hip_angle_range (0.6593) is low and worsening, goal >0.8.
    # Encourage the hip of the swinging leg to move forward (positive angle), promoting a full stride.
    swing_hip_reward_component = 0.0
    if is_right_foot_in_air: # Right leg is swinging
        swing_hip_reward_component += max(0, hip_1_angle) # Reward positive hip angle (leg forward)
    if is_left_foot_in_air: # Left leg is swinging
        swing_hip_reward_component += max(0, hip_2_angle) # Reward positive hip angle (leg forward)
    
    reward += 0.2 * swing_hip_reward_component

    # --- 7. Penalize Vertical Velocity ---
    # Discourage excessive vertical movement (hopping) to promote smooth horizontal walking.
    reward -= 0.05 * abs(vertical_velocity)
    
    # --- 8. Penalize Excessive Hull Angular Velocity ---
    # Promote a steady and stable torso, reducing wobbling.
    reward -= 0.05 * abs(hull_angular_velocity)

    return reward
