# Auto-generated by LLM — do not edit by hand.
# Modify llm/prompt_builder.py or logs/human_hint.txt to influence the next iteration.

import numpy as np

import numpy as np

def compute_reward(obs, action):
    # --- Reward Weights and Constants ---

    # Basic Locomotion & Stability (Goal 1, 3, 4)
    FORWARD_VELOCITY_WEIGHT = 1.25  # Slightly increased to encourage faster movement (avg_speed ↑)
    HULL_ANGLE_PENALTY_WEIGHT = 7.0   # Increased significantly due to 100% fall rate (torso_tilt ↓)
    HULL_ANG_VEL_PENALTY_WEIGHT = 7.0 # Increased significantly due to 100% fall rate (torso_tilt_variance ↓)
    ACTION_COST_WEIGHT = 0.001        # Standard value for energy efficiency and smoothness (energy_consumption ↓, action_smoothness ↓)

    # Gait Cycle (Goal 2) - Crucial for human-like walking and fall elimination
    CONTACT_THRESHOLD = 0.1           # Minimum contact value to consider a foot on the ground
    FLIGHT_PENALTY = -6.0             # Heavy penalty for both feet off ground (flight_fraction ≈ 0)
    SINGLE_SUPPORT_REWARD = 2.5       # Strong reward for one leg in swing, one in stance (single_support_fraction ≈ 0.65)
    DOUBLE_SUPPORT_PENALTY = -1.0     # Moderate penalty for too much double support (double_support_fraction ≈ 0.15)

    # Leg Mechanics & Coordination (Goal 7)
    SWING_HIP_FORWARD_WEIGHT = 0.7    # Reward hip moving forward during swing phase
    SWING_KNEE_BEND_WEIGHT = 0.4      # Reward knee bending for clearance during swing phase
    STANCE_KNEE_STRAIGHT_PENALTY_WEIGHT = -1.0 # Penalize bent knee during stance phase (stance_leg_straightness < 0.3)
    STANCE_HIP_PROPEL_WEIGHT = 0.6    # Reward hip contributing to forward propulsion during stance phase

    # --- Observation Unpacking ---
    hull_angle = obs[0]
    hull_angular_velocity = obs[1]
    x_velocity = obs[2] # Forward (x) velocity
    
    right_hip_angle = obs[4]
    right_knee_angle = obs[6]
    right_contact = obs[8] # Right foot ground contact (0 = air, 1 = ground)
    
    left_hip_angle = obs[9]
    left_knee_angle = obs[11]
    left_contact = obs[13] # Left foot ground contact (0 = air, 1 = ground)

    # --- Reward Calculation ---
    reward = 0.0

    # 1. Forward Progress
    reward += FORWARD_VELOCITY_WEIGHT * x_velocity

    # 2. Upright Posture & Stability (Primary for fall elimination)
    reward -= HULL_ANGLE_PENALTY_WEIGHT * np.abs(hull_angle)
    reward -= HULL_ANG_VEL_PENALTY_WEIGHT * np.abs(hull_angular_velocity)

    # 3. Energy Efficiency & Action Smoothness
    reward -= ACTION_COST_WEIGHT * np.sum(np.square(action))

    # --- Gait Cycle Rewards (Critical for human-like walking and stability) ---
    right_foot_on_ground = right_contact > CONTACT_THRESHOLD
    left_foot_on_ground = left_contact > CONTACT_THRESHOLD

    if not right_foot_on_ground and not left_foot_on_ground:
        # Both feet off ground: Flight phase (highly undesirable for walking)
        reward += FLIGHT_PENALTY
    elif (right_foot_on_ground and not left_foot_on_ground) or \
         (left_foot_on_ground and not right_foot_on_ground):
        # Exactly one foot on ground: Single support phase (desired walking state, promotes alternation)
        reward += SINGLE_SUPPORT_REWARD
    elif right_foot_on_ground and left_foot_on_ground:
        # Both feet on ground: Double support phase (some is good for stability, too much is shuffling)
        reward += DOUBLE_SUPPORT_PENALTY
        
    # --- Leg Mechanics for Human-like Gait (Promotes proper limb movement) ---

    # Right Leg
    if not right_foot_on_ground: # Right leg is swinging
        # Reward hip moving forward (positive angle) and knee bending (positive angle) for clearance
        reward += SWING_HIP_FORWARD_WEIGHT * max(0, right_hip_angle) 
        reward += SWING_KNEE_BEND_WEIGHT * max(0, right_knee_angle) 
    else: # Right leg is in stance
        # Penalize bent knee (positive angle) for leg straightness
        reward += STANCE_KNEE_STRAIGHT_PENALTY_WEIGHT * max(0, right_knee_angle)
        # Reward hip pushing forward (positive hip angle) only if contributing to forward velocity
        reward += STANCE_HIP_PROPEL_WEIGHT * max(0, right_hip_angle) * x_velocity

    # Left Leg (Symmetrical to Right Leg)
    if not left_foot_on_ground: # Left leg is swinging
        reward += SWING_HIP_FORWARD_WEIGHT * max(0, left_hip_angle)
        reward += SWING_KNEE_BEND_WEIGHT * max(0, left_knee_angle)
    else: # Left leg is in stance
        reward += STANCE_KNEE_STRAIGHT_PENALTY_WEIGHT * max(0, left_knee_angle)
        reward += STANCE_HIP_PROPEL_WEIGHT * max(0, left_hip_angle) * x_velocity

    return float(reward)
