# Auto-generated by LLM — do not edit by hand.
# Modify llm/prompt_builder.py or logs/human_hint.txt to influence the next iteration.

import numpy as np

import numpy as np

def compute_reward(obs, action):
    reward = 0.0

    # Extract relevant observations
    hull_angle = obs[0]
    hull_angular_vel = obs[1]
    forward_vel = obs[2]
    vertical_vel = obs[3]
    right_hip_angle = obs[4]
    right_knee_angle = obs[6]
    right_foot_contact = obs[8]
    left_hip_angle = obs[9]
    left_knee_angle = obs[11]
    left_foot_contact = obs[13]

    # --- 1. ELIMINATE FALLS (Highest Priority) ---
    # The environment already has penalties for hull angle and angular velocity.
    # We add stronger penalties for critical instability to address the 100% fall rate.

    # Target hull angle for a slight forward lean: 0.08 radians (approx 4.5 degrees)
    target_hull_angle = 0.08
    # Penalize deviation from target hull angle, especially large deviations.
    # Squaring makes the penalty increase quadratically with deviation.
    reward -= 15.0 * np.square(hull_angle - target_hull_angle)

    # Catastrophic fall penalty: if hull angle is too extreme or falling rapidly.
    # This provides a strong, immediate signal against falling.
    if np.abs(hull_angle) > 0.8: # Roughly 45 degrees from upright, indicating impending fall
        reward -= 25.0
    if vertical_vel < -0.8: # Rapidly falling downwards
        reward -= 25.0

    # --- 2. ACHIEVE HUMAN-LIKE GAIT CYCLE ---
    # Encourage single support, penalize excessive double support and flight.
    # Target values: single_support_fraction ≈ 0.65, double_support_fraction ≈ 0.15, flight_fraction ≈ 0.0

    is_right_foot_on_ground = right_foot_contact > 0.5
    is_left_foot_on_ground = left_foot_contact > 0.5

    # Single Support Phase: One foot on ground, the other in air (core of walking).
    if (is_right_foot_on_ground and not is_left_foot_on_ground) or \
       (not is_right_foot_on_ground and is_left_foot_on_ground):
        reward += 1.0 # Strong base reward for achieving desired single support.

        # Reward specific leg mechanics for stance and swing phases.
        if is_right_foot_on_ground: # Right leg stance, left leg swing
            # Stance leg (right) knee should be relatively straight for efficiency.
            reward -= 1.0 * np.square(right_knee_angle)
            # Swing leg (left) hip should move through a good range for propulsion/step size.
            reward += 0.4 * np.abs(left_hip_angle)
            # Swing leg (left) knee: Encourage natural bend then extension. Penalize extremes.
            # Target mid-swing bend around 1.0 radians.
            if left_knee_angle < 0.1 or left_knee_angle > 2.0:
                 reward -= 0.2 * np.square(left_knee_angle - 1.0)
        else: # Left leg stance, right leg swing (symmetric logic)
            reward -= 1.0 * np.square(left_knee_angle)
            reward += 0.4 * np.abs(right_hip_angle)
            if right_knee_angle < 0.1 or right_knee_angle > 2.0:
                 reward -= 0.2 * np.square(right_knee_angle - 1.0)

    # Double Support Phase: Both feet on ground. Current value is too high (0.48).
    elif is_right_foot_on_ground and is_left_foot_on_ground:
        reward -= 0.5 # Moderate penalty to reduce excessive double support.
        # Encourage knees to be relatively straight during double support for stable posture.
        reward -= 0.5 * np.square(right_knee_angle)
        reward -= 0.5 * np.square(left_knee_angle)

    # Flight Phase: Both feet in air (undesirable for walking, indicates hopping/running).
    elif not is_right_foot_on_ground and not is_left_foot_on_ground:
        reward -= 2.0 # Heavy penalty for any flight phase.

    # Hip Angle Range (to encourage adequate step size, as per researcher hint 12-15cm):
    # Penalize hip angles that fall outside a propulsive and natural range (e.g., too restricted or overextended).
    # Desired `hip_angle_range` > 0.8 rad. We encourage movement within [-0.6, 1.2] radians.
    hip_angle_deviation_penalty_weight = 0.3
    hip_angle_deviation_penalty = 0.0
    hip_angle_deviation_penalty += np.maximum(0, right_hip_angle - 1.2)
    hip_angle_deviation_penalty += np.maximum(0, -0.6 - right_hip_angle)
    hip_angle_deviation_penalty += np.maximum(0, left_hip_angle - 1.2)
    hip_angle_deviation_penalty += np.maximum(0, -0.6 - left_hip_angle)
    reward -= hip_angle_deviation_penalty_weight * hip_angle_deviation_penalty

    # --- 3. FORWARD PROGRESS ---
    # The environment already rewards `hull.velocity[0]`. We amplify it for speeds within target range.
    # Target speed: 0.05-0.15 m/s normalised.
    forward_progress_reward = 3.0 * np.clip(forward_vel, 0.0, 0.15)
    reward += forward_progress_reward

    # --- 4. UPRIGHT POSTURE ---
    # Hull angle penalties are covered under fall prevention. Hull angular velocity is partially
    # covered by the environment's base reward (`5e-3 * np.square(self.hull.angularVelocity)`).

    # --- 5. ENERGY EFFICIENCY & 6. SMOOTH ACTIONS ---
    # The environment's base reward already includes `1e-3 * np.square(action).sum()`
    # for joint power, which implicitly encourages energy efficiency and smoother actions.
    # No additional explicit penalties added here, as current energy metrics are improving.

    # --- 7. GOOD HIP-KNEE COORDINATION ---
    # This is implicitly encouraged by the specific rewards for stance leg straightness
    # and swing leg hip/knee movements, as well as hip angle range.

    # --- Clipping the final reward ---
    # Prevents excessively large positive or negative rewards/penalties, which can destabilize training.
    reward = np.clip(reward, -75.0, 75.0)

    return reward
