# Auto-generated by LLM — do not edit by hand.
# Modify llm/prompt_builder.py or logs/human_hint.txt to influence the next iteration.

import numpy as np

import numpy as np

def compute_reward(obs, action):
    # Unpack observations for readability
    hull_angle = obs[0]
    hull_angular_velocity = obs[1]
    forward_velocity = obs[2]
    vertical_velocity = obs[3]

    # Right Leg (Leg 1)
    hip_1_angle = obs[4]
    hip_1_angular_speed = obs[5]
    knee_1_angle = obs[6]
    knee_1_angular_speed = obs[7]
    leg_1_contact = obs[8] # Right foot contact (0 = air, 1 = ground)

    # Left Leg (Leg 2)
    hip_2_angle = obs[9]
    hip_2_angular_speed = obs[10]
    knee_2_angle = obs[11]
    knee_2_angular_speed = obs[12]
    leg_2_contact = obs[13] # Left foot contact (0 = air, 1 = ground)

    # Initialize reward
    reward = 0.0

    # 1. Forward Progress (Goal 3)
    # Reward for moving forward. Strongly penalize backward motion.
    forward_reward = forward_velocity * 2.0
    if forward_velocity < 0:
        forward_reward *= 3.0  # Penalize backward movement more heavily
    reward += forward_reward

    # 2. Posture & Stability (Goal 4 & implicitly Goal 1: ELIMINATE FALLS)
    # Penalize large hull angles (leaning too much, both forward and backward)
    hull_angle_penalty = -np.abs(hull_angle) * 3.0
    reward += hull_angle_penalty

    # Penalize high hull angular velocity (wobbling)
    hull_angular_velocity_penalty = -np.abs(hull_angular_velocity) * 0.1
    reward += hull_angular_velocity_penalty

    # Penalize excessive vertical velocity downwards (falling fast) - primary fall deterrent
    if vertical_velocity < -0.5: # Threshold for rapid descent
        reward -= 15.0 # Very heavy penalty for clear falling
    elif vertical_velocity < 0:
        reward -= np.abs(vertical_velocity) * 3.0 # Moderate penalty for any downward motion

    # 3. Energy Efficiency (Goal 5) & Smooth Actions (Goal 6)
    # Penalize sum of squared actions (torque usage)
    energy_penalty = -np.sum(np.square(action)) * 0.0005 # Small penalty to encourage efficiency without hindering learning gait
    reward += energy_penalty

    # 4. Human-like Gait Cycle (Goal 2 & implicitly Goal 1: ELIMINATE FALLS)
    # This is critical for improving stability and achieving a natural walking pattern.

    # Contact states
    right_foot_on_ground = leg_1_contact > 0.5 # Use >0.5 for robustness against floating point
    left_foot_on_ground = leg_2_contact > 0.5

    both_feet_on_ground = right_foot_on_ground and left_foot_on_ground
    one_foot_on_ground = (right_foot_on_ground != left_foot_on_ground) # XOR
    no_feet_on_ground = not (right_foot_on_ground or left_foot_on_ground)

    # Penalize flight (both feet off ground) heavily for walking
    if no_feet_on_ground:
        reward -= 6.0 # Very strong penalty: target flight_fraction ≈ 0
    
    # Reward for Double Support: Current 0.025, target ~0.15. Needs increase.
    if both_feet_on_ground:
        reward += 0.3 # Positive reward to encourage brief double support phase

    # Single Support Rewards/Penalties: Current 0.946, target ~0.65.
    # The agent is spending too much unstable time in single support, leading to falls.
    if one_foot_on_ground:
        # Penalize if hull is very unstable during single support (prevents falling while balancing)
        if np.abs(hull_angle) > 0.25 or np.abs(hull_angular_velocity) > 0.8: # Tunable thresholds for instability
            reward -= 2.5 # Significant penalty for unstable single support
        else:
            reward += 0.6 # Reward for stable single support

    # Alternating swing/stance logic (right-swing/left-stance OR left-swing/right-stance)
    # This promotes coordinated leg movement and a smooth gait.

    # Right leg swing (foot off ground), Left leg stance (foot on ground)
    if not right_foot_on_ground and left_foot_on_ground:
        # Right (swing) leg:
        # Encourage hip flexion (leg forward) for swing
        reward += np.clip(hip_1_angle * 0.7, 0, 0.7) # Reward for positive hip angle
        # Encourage knee flexion (bent) for ground clearance during swing
        knee_1_bend_target = 0.6 # Approximately 34 degrees
        reward += -np.abs(knee_1_angle - knee_1_bend_target) * 0.6

        # Left (stance) leg:
        # Encourage knee extension (straight) for stable support
        reward -= np.abs(knee_2_angle) * 1.5 # Strong penalty for bent stance knee (target <0.3)
        # Encourage hip extension/neutral for push-off
        hip_2_stance_target = -0.15 # Slightly extended hip
        reward += -np.abs(hip_2_angle - hip_2_stance_target) * 0.3

    # Left leg swing (foot off ground), Right leg stance (foot on ground)
    elif not left_foot_on_ground and right_foot_on_ground:
        # Left (swing) leg:
        # Encourage hip flexion (leg forward)
        reward += np.clip(hip_2_angle * 0.7, 0, 0.7)
        # Encourage knee flexion (bent)
        knee_2_bend_target = 0.6
        reward += -np.abs(knee_2_angle - knee_2_bend_target) * 0.6

        # Right (stance) leg:
        # Encourage knee extension (straight)
        reward -= np.abs(knee_1_angle) * 1.5
        # Encourage hip extension/neutral
        hip_1_stance_target = -0.15
        reward += -np.abs(hip_1_angle - hip_1_stance_target) * 0.3
        
    # Optional: Encourage good hip-knee coordination (Goal 7) indirectly.
    # The specific knee/hip angle targets for swing/stance already encourage this.
    # For instance, a positive hip_angle reward for swing leg complements the knee_bend_target.

    return reward
