# Auto-generated by LLM — do not edit by hand.
# Modify llm/prompt_builder.py or logs/human_hint.txt to influence the next iteration.

import numpy as np

import numpy as np

def compute_reward(obs, action):
    # Constants for reward shaping. Tuned to prioritize stability, preventing falls,
    # and establishing core human-like gait mechanics.
    FORWARD_VEL_WEIGHT = 2.0
    TORQUE_PENALTY_WEIGHT = 0.00035
    HULL_ANGLE_PENALTY_WEIGHT = 6.0      # Increased: strong penalty for hull tilt (0 = upright)
    HULL_ANG_VEL_PENALTY_WEIGHT = 0.75   # Increased: penalty for torso wobbling
    DOWNWARD_VEL_PENALTY_WEIGHT = 25.0   # Significantly increased: very strong penalty for falling downwards
    STANCE_KNEE_BEND_PENALTY_WEIGHT = 15.0 # Significantly increased: crucial for efficient and stable stance
    FLIGHT_PENALTY_WEIGHT = 12.0         # Increased: discourage hopping, encourage walking
    DOUBLE_SUPPORT_BONUS = 0.4           # Increased: encourage brief double support for smoother transitions
    SINGLE_SUPPORT_BONUS = 0.6           # Increased: encourage alternating single support for leg swing
    STANCE_HIP_EXTENSION_REWARD_WEIGHT = 3.5 # Increased: reward powerful push-off during stance

    # Unpack observations for clarity
    hull_angle = obs[0]             # Torso angle (0 = upright)
    hull_angular_velocity = obs[1]  # Torso angular velocity
    x_velocity = obs[2]             # Forward velocity (main locomotion signal)
    y_velocity = obs[3]             # Vertical velocity

    # Right leg observations
    right_hip_angle = obs[4]
    right_knee_angle = obs[6]
    right_contact = obs[8]          # 1 if right foot on ground, 0 otherwise

    # Left leg observations
    left_hip_angle = obs[9]
    left_knee_angle = obs[11]
    left_contact = obs[13]          # 1 if left foot on ground, 0 otherwise

    # Initialize reward
    reward = 0.0

    # 1. FORWARD PROGRESS (Goal 3)
    # Reward for moving forward.
    reward += x_velocity * FORWARD_VEL_WEIGHT

    # 2. ENERGY EFFICIENCY & SMOOTH ACTIONS (Goal 5 & 6)
    # Penalize large torques to encourage energy efficiency and smoother actions.
    reward -= TORQUE_PENALTY_WEIGHT * np.sum(np.square(action))

    # 3. UPRIGHT POSTURE & ELIMINATE FALLS (Goal 1 & 4)
    # Strong penalty for hull angle deviation from upright (0 radians).
    reward -= np.abs(hull_angle) * HULL_ANGLE_PENALTY_WEIGHT
    # Penalty for high angular velocity of the hull, indicating instability/wobbling.
    reward -= np.abs(hull_angular_velocity) * HULL_ANG_VEL_PENALTY_WEIGHT
    # Very strong penalty for negative vertical velocity (falling downwards).
    reward -= np.maximum(0, -y_velocity) * DOWNWARD_VEL_PENALTY_WEIGHT

    # 4. STANCE LEG STRAIGHTNESS (Goal 2, important for efficiency and stability)
    # Penalize bent knees (positive angle) when the foot is on the ground.
    # Squaring the angle makes larger bends much more costly.
    # This addresses the 'stance_leg_straightness' metric.
    reward -= (right_contact * right_knee_angle**2 +
               left_contact * left_knee_angle**2) * STANCE_KNEE_BEND_PENALTY_WEIGHT

    # 5. GAIT CYCLE SHAPING (Goal 2: ACHIEVE HUMAN-LIKE GAIT CYCLE)
    # Determine contact states:
    flight_status = (1 - right_contact) * (1 - left_contact) # Both feet in air
    double_contact_status = right_contact * left_contact       # Both feet on ground
    single_support_status = 1 - flight_status - double_contact_status # One foot on ground

    # Penalize flight heavily to ensure walking, not hopping/running.
    # This helps achieve flight_fraction ≈ 0.
    reward -= flight_status * FLIGHT_PENALTY_WEIGHT

    # Reward for being in single support. This encourages the agent to lift one leg,
    # which is essential for walking. It helps target single_support_fraction ≈ 0.65.
    reward += single_support_status * SINGLE_SUPPORT_BONUS

    # Reward for brief double support. This helps with smooth transitions between single
    # support phases and targets double_support_fraction ≈ 0.15, while discouraging shuffling.
    reward += double_contact_status * DOUBLE_SUPPORT_BONUS

    # 6. STANCE HIP EXTENSION (Goal 7: GOOD HIP-KNEE COORDINATION, FORWARD PROGRESS)
    # Reward for extending the hip backward (negative hip angle) when the leg is in contact.
    # This mimics the propulsive phase of human walking and encourages a good hip angle range.
    # `max(0, -angle)` ensures reward only for extension.
    reward += (right_contact * np.maximum(0, -right_hip_angle) +
               left_contact * np.maximum(0, -left_hip_angle)) * STANCE_HIP_EXTENSION_REWARD_WEIGHT

    return float(reward)
