# Auto-generated by LLM — do not edit by hand.
# Modify llm/prompt_builder.py or logs/human_hint.txt to influence the next iteration.

import numpy as np

import numpy as np

def compute_reward(obs, action):
    reward = 0.0

    # Observation unpacking for readability
    hull_angle = obs[0]
    hull_angular_velocity = obs[1]
    x_velocity = obs[2]
    # y_velocity = obs[3] # Not directly used in this iteration
    hip_right_angle = obs[4]
    hip_right_angular_speed = obs[5]
    knee_right_angle = obs[6]
    knee_right_angular_speed = obs[7]
    right_foot_contact = obs[8] > 0.5
    hip_left_angle = obs[9]
    hip_left_angular_speed = obs[10]
    knee_left_angle = obs[11]
    knee_left_angular_speed = obs[12]
    left_foot_contact = obs[13] > 0.5
    # lidar_readings = obs[14:24] # Not directly used for flat terrain

    # Action unpacking
    # hip_right_torque = action[0] # Not directly used, covered by energy penalty
    # knee_right_torque = action[1]
    # hip_left_torque = action[2]
    # knee_left_torque = action[3]

    # === 1. ELIMINATE FALLS & UPRIGHT POSTURE ===
    # Penalize large hull angles (falling) and reward a slight forward lean.
    # The agent always falls (100%), so this is critical.
    TARGET_HULL_ANGLE = 0.08  # Radians, slight forward lean (0.05-0.15 is ideal)
    HULL_ANGLE_TOLERANCE = 0.3 # Radians, acceptable range around target
    HULL_ANGLE_REWARD_SCALE = 2.0
    HULL_ANGLE_PENALTY_SCALE = 15.0 # Heavy penalty for falling over

    hull_angle_deviation = np.abs(hull_angle - TARGET_HULL_ANGLE)
    if hull_angle_deviation < HULL_ANGLE_TOLERANCE:
        reward += HULL_ANGLE_REWARD_SCALE * (HULL_ANGLE_TOLERANCE - hull_angle_deviation)
    else:
        reward -= HULL_ANGLE_PENALTY_SCALE * hull_angle_deviation

    # Penalize high angular velocity of the hull (wobbling)
    # Lateral stability is good, ensure it stays that way.
    reward -= 0.1 * np.abs(hull_angular_velocity)

    # === 2. FORWARD PROGRESS ===
    # Average speed is low, needs significant boost.
    reward += 3.0 * x_velocity

    # === 3. ENERGY EFFICIENCY ===
    # Energy consumption is worsening. Penalize action magnitude.
    joint_effort_penalty = 0.005 * np.sum(np.square(action))
    reward -= joint_effort_penalty

    # === 4. ACHIEVE HUMAN-LIKE GAIT CYCLE ===
    # Prioritize single support, penalize flight, allow some double support.
    # Current: flight_fraction=0.024 (too high), single_support_fraction=0.939 (too high),
    # double_support_fraction=0.037 (too low), contact_per_metre=20.8 (shuffling).
    
    right_leg_swing = not right_foot_contact
    left_leg_swing = not left_foot_contact
    right_leg_stance = right_foot_contact
    left_leg_stance = left_foot_contact

    # Single Support Phase: One foot on ground, one foot in air. Most important for walking.
    if (right_leg_stance and left_leg_swing) or (left_leg_stance and right_leg_swing):
        reward += 1.5 # Strong reward for stable single support

    # Double Support Phase: Both feet on ground. Brief transition.
    # Current double support is too low, but contact_per_metre is too high suggesting 'shuffling'.
    # A small reward encourages true double support without promoting shuffling.
    if right_leg_stance and left_leg_stance:
        reward += 0.3

    # Flight Phase: Both feet in air. Heavy penalty for walking robot.
    if right_leg_swing and left_leg_swing:
        reward -= 5.0 # Very heavy penalty

    # === 5. HIP & KNEE COORDINATION & GAIT MECHANICS ===
    # Stance Leg Straightness (knee not bent much when on ground)
    # Stance_leg_straightness is good, maintain it.
    KNEE_STRAIGHTNESS_PENALTY_SCALE = 0.3
    if right_leg_stance:
        reward -= KNEE_STRAIGHTNESS_PENALTY_SCALE * np.abs(knee_right_angle)
    if left_leg_stance:
        reward -= KNEE_STRAIGHTNESS_PENALTY_SCALE * np.abs(knee_left_angle)

    # Swing Leg Flexion (knee bent during swing)
    # Encourage positive knee angle (flexion) when leg is in air.
    KNEE_FLEXION_REWARD_SCALE = 0.2
    MAX_KNEE_FLEXION_ANGLE = 1.0 # Radians, reasonable maximum bend to reward
    if right_leg_swing:
        reward += KNEE_FLEXION_REWARD_SCALE * np.clip(knee_right_angle, 0.0, MAX_KNEE_FLEXION_ANGLE)
    if left_leg_swing:
        reward += KNEE_FLEXION_REWARD_SCALE * np.clip(knee_left_angle, 0.0, MAX_KNEE_FLEXION_ANGLE)

    # Hip Movement during Swing
    # Encourage hip angular velocity during swing to promote leg movement and range of motion.
    HIP_SWING_VELOCITY_REWARD_SCALE = 0.08
    if right_leg_swing:
        reward += HIP_SWING_VELOCITY_REWARD_SCALE * np.abs(hip_right_angular_speed)
    if left_leg_swing:
        reward += HIP_SWING_VELOCITY_REWARD_SCALE * np.abs(hip_left_angular_speed)
        
    return float(reward)
