# Auto-generated by LLM — do not edit by hand.
# Modify llm/prompt_builder.py or logs/human_hint.txt to influence the next iteration.

import numpy as np

import numpy as np

def compute_reward(obs, action):
    # --- Observation aliases for readability ---
    hull_angle = obs[0]
    hull_angular_velocity = obs[1]
    forward_velocity = obs[2]
    
    right_hip_angle = obs[4]
    right_knee_angle = obs[6]
    right_foot_contact = obs[8]
    
    left_hip_angle = obs[9]
    left_knee_angle = obs[11]
    left_foot_contact = obs[13]

    # --- Reward Components ---

    # 1. Forward Progress (Goal 3: average_speed ↑)
    # Reward strongly for positive forward velocity. Current speed is very low.
    forward_reward = forward_velocity * 3.5 

    # 2. Upright Posture & Stability (Goal 4: torso_tilt ↓, torso_tilt_variance ↓)
    # Penalize deviation from a slight forward lean (target_hull_angle = 0.1 rad).
    # Current torso_tilt is 0.1775, slightly high.
    target_hull_angle = 0.1  # Human-like walking often involves a slight forward lean
    hull_angle_penalty = np.abs(hull_angle - target_hull_angle) * 8.0 
    
    # Penalize high angular velocity to reduce wobbling and improve stability.
    hull_angular_velocity_penalty = np.abs(hull_angular_velocity) * 0.7 

    # 3. Energy Efficiency & Smooth Actions (Goal 5 & 6: energy_consumption ↓, action_smoothness ↓)
    # Penalize large action magnitudes (torques). Keep penalty moderate.
    action_cost = np.sum(np.square(action)) * 0.007

    # 4. Survival (Goal 1: ELIMINATE FALLS)
    # A small constant reward per step encourages the agent to stay alive.
    # Crucial given the 100% fall rate.
    survival_reward = 0.2

    # 5. Human-like Gait Cycle (Goal 2: balanced single/double support, no flight)
    
    # Single Support (one foot on ground, one off) - Target ~0.65
    # Current single_support_fraction: 0.952 (too high, agent likely unstable)
    # Provide a bonus for being in a single support phase.
    is_single_support = ((right_foot_contact == 1) != (left_foot_contact == 1))
    single_support_bonus = is_single_support * 0.5

    # Double Support (both feet on ground) - Target ~0.15
    # Current double_support_fraction: 0.018 (too low, needs to be increased)
    # Reward for being in double support to encourage this phase of the gait.
    is_double_support = (right_foot_contact == 1) and (left_foot_contact == 1)
    double_support_reward = is_double_support * 0.6 

    # Flight (both feet off ground) - Target ~0.0
    # Current flight_fraction: 0.030 (needs to be reduced)
    # Heavily penalize both feet being off the ground; walking, not hopping.
    is_flight = (right_foot_contact == 0) and (left_foot_contact == 0)
    flight_penalty = is_flight * 3.0

    # 6. Stance Leg Straightness (Goal 7: stance_leg_straightness ↓)
    # Penalize bent knees when a leg is in contact with the ground (stance phase).
    # Current stance_leg_straightness: 0.3231 (close to target <0.3).
    stance_knee_penalty = 0.0
    if right_foot_contact == 1:
        stance_knee_penalty += np.abs(right_knee_angle) * 0.4
    if left_foot_contact == 1:
        stance_knee_penalty += np.abs(left_knee_angle) * 0.4
    
    # --- Combine all reward components ---
    total_reward = (
        forward_reward
        - hull_angle_penalty
        - hull_angular_velocity_penalty
        - action_cost
        + survival_reward
        + single_support_bonus
        + double_support_reward
        - flight_penalty
        - stance_knee_penalty
    )

    return total_reward
