# Auto-generated by LLM — do not edit by hand.
# Modify llm/prompt_builder.py or logs/human_hint.txt to influence the next iteration.

import numpy as np

import numpy as np

def compute_reward(obs, action):
    # Constants for reward shaping
    # --- Goal 3: Forward Progress ---
    X_VEL_WEIGHT = 3.5 # Significantly increase reward for forward velocity to initiate movement

    # --- Goal 4: Upright Posture ---
    HULL_ANG_VEL_PENALTY_WEIGHT = -0.15 # Penalize hull angular velocity (wobbling)
    HULL_ANGLE_PENALTY_WEIGHT = -0.4 # Penalize deviation from a target forward lean
    TARGET_HULL_ANGLE = 0.08 # Ideal slight forward lean (rad) for walking stability

    # --- Goal 5 & 6: Energy Efficiency & Smoothness ---
    ENERGY_PENALTY_WEIGHT = -0.008 # Penalize large action magnitudes (energy consumption)

    # --- Goal 2: Human-like Gait Cycle ---
    SINGLE_SUPPORT_REWARD_WEIGHT = 2.0 # Strongly reward for having one foot on ground
    DOUBLE_SUPPORT_PENALTY_WEIGHT = -2.0 # Strongly penalize both feet on ground (currently too high)
    FLIGHT_PENALTY_WEIGHT = -1.0 # Penalize both feet off ground (researcher hint: avoid excessive flight times)

    # --- Goal 2 & 7: Stance Leg Straightness & Hip Range for step size ---
    STANCE_KNEE_BENT_PENALTY_WEIGHT = -2.0 # Heavily penalize bent knees when foot is on the ground
    SWING_HIP_RANGE_REWARD_WEIGHT = 1.0 # Encourage significant hip movement during swing for larger steps

    # --- Observation values ---
    hull_angle = obs[0]
    hull_angular_velocity = obs[1]
    x_velocity = obs[2]
    
    hip1_angle = obs[4] # Right hip angle
    knee1_angle = obs[6] # Right knee angle
    leg1_contact = obs[8] # Right foot ground contact (0=air, 1=ground)

    hip2_angle = obs[9] # Left hip angle
    knee2_angle = obs[11] # Left knee angle
    leg2_contact = obs[13] # Left foot ground contact (0=air, 1=ground)

    reward = 0.0

    # 1. Forward Progress (Goal 3) - Primary driver for movement
    reward += x_velocity * X_VEL_WEIGHT

    # 2. Posture & Stability (Goal 4)
    reward += abs(hull_angular_velocity) * HULL_ANG_VEL_PENALTY_WEIGHT
    reward += abs(hull_angle - TARGET_HULL_ANGLE) * HULL_ANGLE_PENALTY_WEIGHT

    # 3. Energy Consumption (Goal 5)
    reward += np.sum(np.square(action)) * ENERGY_PENALTY_WEIGHT

    # 4. Human-like Gait Cycle (Goal 2)
    # Promote single support (one leg swinging, one leg in stance)
    # Penalize double support (both feet on ground) and flight phase (both feet off ground)
    is_right_leg_stance = leg1_contact > 0.5
    is_left_leg_stance = leg2_contact > 0.5

    if is_right_leg_stance and is_left_leg_stance: # Double support
        reward += DOUBLE_SUPPORT_PENALTY_WEIGHT
    elif not is_right_leg_stance and not is_left_leg_stance: # Flight phase
        reward += FLIGHT_PENALTY_WEIGHT
    else: # Single support (one leg stance, one leg swing)
        reward += SINGLE_SUPPORT_REWARD_WEIGHT

    # 5. Stance Leg Straightness (Goal 2/7)
    # Penalize bent knees when the leg is in stance phase
    if is_right_leg_stance:
        reward += abs(knee1_angle) * STANCE_KNEE_BENT_PENALTY_WEIGHT
    if is_left_leg_stance:
        reward += abs(knee2_angle) * STANCE_KNEE_BENT_PENALTY_WEIGHT
    
    # 6. Step Size / Hip Range (Goal 2/7)
    # Encourage a good range of motion in the hips during the swing phase to promote larger steps
    if not is_right_leg_stance: # Right leg is swinging
        reward += abs(hip1_angle) * SWING_HIP_RANGE_REWARD_WEIGHT
    if not is_left_leg_stance: # Left leg is swinging
        reward += abs(hip2_angle) * SWING_HIP_RANGE_REWARD_WEIGHT
    
    return float(reward)
