# Auto-generated by LLM — do not edit by hand.
# Modify llm/prompt_builder.py or logs/human_hint.txt to influence the next iteration.

import numpy as np

import numpy as np

def compute_reward(obs, action):
    # Constants for reward shaping
    # Prioritize speed and gait cycle improvements based on performance metrics and goals
    VELOCITY_WEIGHT = 3.0  # Increased weight: average_speed is low (0.028), needs to be 0.05-0.15
    HULL_ANGLE_PENALTY = 2.5 # Increased penalty: torso_tilt is worsening (0.2798 rad)
    HULL_ANGULAR_VEL_PENALTY = 0.15 # Slightly increased
    ENERGY_PENALTY = 0.00035 # Standard penalty for BipedalWalker environment
    FLIGHT_PENALTY = 3.0 # Strong penalty: flight_fraction is too high (0.060), needs to be ~0
    DOUBLE_SUPPORT_REWARD = 0.8 # Increased reward: double_support_fraction is too low (0.001), needs to be ~0.15
    PROPULSION_WEIGHT = 0.7 # Increased reward for effective push-off to improve speed and gait
    KNEE_BEND_STANCE_PENALTY = 0.4 # Maintain straightness of stance leg; current value is good (0.0777)

    # Extract relevant observations
    x_velocity = obs[2]
    hull_angle = obs[0]
    hull_angular_velocity = obs[1]
    
    right_hip_angle = obs[4]
    right_knee_angle = obs[6]
    right_foot_contact = obs[8]
    
    left_hip_angle = obs[9]
    left_knee_angle = obs[11]
    left_foot_contact = obs[13]

    reward = 0.0

    # 1. Forward Progress: Reward for moving right (positive x-velocity)
    reward += x_velocity * VELOCITY_WEIGHT

    # 2. Upright Posture: Penalize excessive hull angle and angular velocity
    reward -= np.abs(hull_angle) * HULL_ANGLE_PENALTY
    reward -= np.abs(hull_angular_velocity) * HULL_ANGULAR_VEL_PENALTY

    # 3. Energy Efficiency: Penalize high action magnitudes (sum of squares)
    reward -= np.sum(action**2) * ENERGY_PENALTY

    # 4. Gait Cycle - Flight Penalty: Penalize if both feet are in the air (address flight_fraction)
    # This directly addresses the researcher hint about penalizing excessive flight times.
    is_flying = (1.0 - right_foot_contact) * (1.0 - left_foot_contact)
    reward -= is_flying * FLIGHT_PENALTY

    # 5. Gait Cycle - Double Support Reward: Reward for brief double contact (address double_support_fraction)
    # This encourages the necessary transition phase in human-like walking.
    is_double_support = right_foot_contact * left_foot_contact
    reward += is_double_support * DOUBLE_SUPPORT_REWARD

    # 6. Propulsion Reward: Encourage hip extension (negative angle) during stance for push-off
    # This promotes efficient forward movement and contributes to a natural gait.
    right_propulsion_active = right_foot_contact * np.maximum(0, -right_hip_angle)
    left_propulsion_active = left_foot_contact * np.maximum(0, -left_hip_angle)
    reward += (right_propulsion_active + left_propulsion_active) * PROPULSION_WEIGHT

    # 7. Stance Leg Straightness Penalty: Penalize bent knees while in stance phase
    # This helps maintain the good 'stance_leg_straightness' metric.
    right_knee_bent_in_stance = right_foot_contact * np.abs(right_knee_angle)
    left_knee_bent_in_stance = left_foot_contact * np.abs(left_knee_angle)
    reward -= (right_knee_bent_in_stance + left_knee_bent_in_stance) * KNEE_BEND_STANCE_PENALTY

    # The remaining gait cycle goals (e.g., gait_symmetry_index, single_support_fraction, step size)
    # are expected to improve as emergent behaviors from the combined effects of rewarding speed,
    # proper contact phases (flight, double support), and efficient propulsion.

    return reward
